### ISSUE TITLE
Cannot find type 'UIApplication' in scope

### ISSUE THREAD

**Issue by andreaslindahl** [tus/TUSKit#102]
I'm using TUSKit (2.1.0) via Swift Package Manager and am suddenly getting some compilation errors in TUSClient.swift, such as "Cannot find type 'UIApplication' in scope". If I use the swift-development branch instead everything compiles just fine.

There seems to be a missing `import UIKit` in the  TUSClient in the 2.1.0 version I'm using.

**Comment by MMasterson** [comment]
Hmm, #100 should've fixed this. Do you know where the missing import is? If not can look for the missing import and add it to the next release this weekend

**Comment by andreaslindahl** [comment]
I think there should be a UIKit import in TUSClient.swift ?

**Comment by tjeerdintveen** [comment]
The latest release has the import UIKit lines, should be solved now (I inherited the project but seems fine). Please reopen if you still have issues.
