### ISSUE TITLE
Bug in Upload cancel

### ISSUE THREAD

**Issue by TimoSeeberger** [tus/TUSKit#103]
Hello, I am using TUSKit 2.1.0. I am pretty sure there is a bug in the Swift code for canceling an active upload.
TUSExecutor.swift, line 222: **if task != nil** should be **if task == nil**
Best regards
Timo

**Comment by hannojg** [comment]
Yeah, good catch https://github.com/tus/TUSKit/pull/104

**Comment by MMasterson** [comment]
Fixed in #104 - will release this weekend

**Comment by Deepak3097** [comment]
Hi @MMasterson, i am facing a similar issue, where videos are not getting cancelled or paused.
Using this for `TUSClient.shared.cancel(forUpload: uploadObject)` for cancelling, and `TUSClient.shared.pause(forUpload: uploadObject)` for pause. Is this bug fixed and released?

**Comment by elvirion** [comment]
I'm closing this issue, because it has been fixed in version 2.2.0
