### ISSUE TITLE
File not found in local storage

### ISSUE THREAD

**Issue by jerrybracegit** [tus/TUSKit#106]
TUSClient > createOrResume is returning false for the fileManager.fileExists check - even though the file is in the TUS directory. Is there a known bug related to this?

**Comment by MMasterson** [comment]
Hey @jerrybracegit what version are you running?

**Comment by jerrybracegit** [comment]
@MMasterson thanks for the quick reply. I was stuck on this for about 3 hours and it was resolved by uninstalling my app and reinstalling. Must have been a weird file structure issue. Thanks again.

**Comment by MMasterson** [comment]
No problem, glad it was fixed up! We'll take a look to see if anything funky is going on just in case.
