### ISSUE TITLE
Bug in handleUploadSuccess() in TUSExecutor

### ISSUE THREAD

**Issue by Deepak3097** [tus/TUSKit#107]
Hello, i am using TUSKIT version 2.1.0, facing an issue where i have paused an upload, and started another upload.
Once the 2nd upload is completed, the paused one also starts uploading automatically.

On debugging found this in `handleUploadSuccess()` ->

`// Run next task for uploading, when there are any.
  if continueUploading() {
       let pendingUploads = TUSClient.shared.pendingUploads()
      TUSClient.shared.createOrResume(forUpload: pendingUploads[0])
  } else {
       completion(true)
  }`

`continueUploading()` -> returns true

`internal func continueUploading() -> Bool {
        let uploadWholeQueueInBackground = TUSClient.config?.backgroundMode == TUSBackgroundMode.PreferUploadQueue
        let isAppBackground = TUSClient.shared.applicationState == .background
        
        let pendingUploads = TUSClient.shared.pendingUploads()
        return pendingUploads.count > 0 && (uploadWholeQueueInBackground || !isAppBackground)
    }`

we have set backgroundMode = PreferUploadQueue, and my app is in foreground.

`TUSClient.shared.pendingUploads()` -> This function only omits `failed` and `finished` uploads, and not `cancelled`/`paused`.
because of this the paused upload resumes.

`public func pendingUploads() -> [TUSUpload] {
        if currentUploads == nil {
            return []
        }
        return currentUploads!.filter({ (_upload) -> Bool in
            return _upload.status != .failed && _upload.status != .finished
        })
    }`

Please correct me if i am wrong anywhere, and please help with a solution/fix for this.
Thank you,
Regards.

**Comment by elvirion** [comment]
I’m closing this issue because it has been inactive. We've recently released 3.0.0. Feel free to open a new issue if this issue remains on version 3.x.x.
