### ISSUE TITLE
Support concurrency

### ISSUE THREAD

**Issue by TaroofSun** [tus/TUSKit#108]
Excuse me, do you support concurrency? I want to send multiple documents together.

**Comment by Acconut** [comment]
I haven't tested it personally yet, but you should be able to create multiple `TUSUpload` instances in parallel and then invoke `TUSClient.shared.createOrResume(uploadObject)` on the corresponding ones to upload them concurrently. Let us know if this does not work, so we can fix it :)

**Comment by yo113** [comment]
> I haven't tested it personally yet, but you should be able to create multiple `TUSUpload` instances in parallel and then invoke `TUSClient.shared.createOrResume(uploadObject)` on the corresponding ones to upload them concurrently. Let us know if this does not work, so we can fix it :)

I have created multiple TUSUpload instances in parallel and invoked TUSClient.shared.createOrResume(uploadObject) but it uploads sequentially one after other and not parallelly.

**Comment by tjeerdintveen** [comment]
Hi, new contributor here. Yeah it's because everything is made with a singleton that controls the way uploading is handled (1 by 1). I am in the middle of a rewrite where I will address this issue (no singletons) and allow for concurrency.

**Comment by elvirion** [comment]
I'm closing this issue. Support for concurrency is added in version 3.0.0
