### ISSUE TITLE
Is this library still being maintained? 

### ISSUE THREAD

**Issue by dfmarulanda** [tus/TUSKit#109]

**Comment by Acconut** [comment]
Yes, although the answer to this question is not clearly cut as we would like. Right now, we are in the process of switching the maintainer of TUSKit over to a new person, which will start contributing to TUSKit at the beginning of September. In the meantime, we will still try our best at answering questions, but code contributions will pick up in a few weeks again! So stay tuned :)

**Comment by nikolay-kapustin** [comment]
Do you have any news about the new version of TUSKit?

**Comment by tjeerdintveen** [comment]
Hi, I just started as a new contributor.

I will investigate releasing the current status. Is there anything in particular you wish to see ?

**Comment by tjeerdintveen** [comment]
I just made a new release, 2.2.0
https://github.com/tus/TUSKit/releases/tag/2.2.0

Let me know if you need anything, I will close this issue. But feel free to reopen for any questions.

**Comment by dfmarulanda** [comment]
@tjeerdintveen thanks! Implementation and documentation by now is so poor; I think an entire rework will be needed, as the way recurrence requests were implemented can lead to leaks. I've done some work to improve that, and I'll send you a PR if you're going to use the same base code. But I was tempted to make my own implementation from scratch because there are many codebase problems.

**Comment by tjeerdintveen** [comment]
I am planning to rework it, starting with internals, giving it a mature testing suite. Simultaneously I will add documentation. I only just began but expect improvements to come. 😊

What do you mean by recurrence requests specifically? I'll keep an extra eye out for that

**Comment by dfmarulanda** [comment]
You know that TUS protocol sends chunk requests; so a request must call the
following; current implementation uses a non-safe way of calling self in
every request; in addition, it doesn't, send the last request as expected,
cuz it doesn't wait for the TUS Server answer, but instead just send all
the request without knowing if the last one was successful; I had to rework
that for my implementation but I made just a bad fix cuz didn't had the
time to rework the entire lib.

**Comment by tjeerdintveen** [comment]
I see, so I am planning for a rewrite to try and squash these bugs. I'll be sure to make sure I don't reintroduce bugs like these. Thanks for letting me know.  It sounds like it would be better to check if one request finishes. But on the other hand, supporting parallel uploads is also an option I believe. I'll investigate.
