### ISSUE TITLE
Lack of merging custom headers when checkForResumableOffset

### ISSUE THREAD

**Issue by fakerlogic** [tus/TUSKit#110]
My upload headers need token, when it goes there, I get the the 401 response

**Comment by fakerlogic** [comment]
`  
  func checkForResumableOffset(uploadUrl: URL, callback: @escaping ((Int?) -> Void)) {
        var headRequest: URLRequest = URLRequest(url: uploadUrl)
        headRequest.httpMethod = "HEAD"
        headRequest.addValue(TUSConstants.TUSProtocolVersion, forHTTPHeaderField: "TUS-Resumable")
        
        for header in customHeaders {
            headRequest.addValue(header.value, forHTTPHeaderField: header.key)
        }
...
`

**Comment by tjeerdintveen** [comment]
Hi thanks, I am new at TUS and starting a rewrite of the SDK. I will look into this requirement.

**Comment by tjeerdintveen** [comment]
If you'd like, you can explore the rewrite PR. See if the custom headers work as you like.
https://github.com/tus/TUSKit/pull/114

**Comment by elvirion** [comment]
I'm closing this issue. Support for customHeaders is added in version 3.0.0
