### ISSUE TITLE
Is remaining bytes really remained or it is a total value of bytes?

### ISSUE THREAD

**Issue by avbikk** [tus/TUSKit#116]
The formula: uploaded/total shows real progress. The formula: uploaded/remaining doesn't make any sense if remaining is the remained number of bytes. It should be uploaded/(uploaded+remaining). 

So, what is the right:
1) here is the incorrect naming
2) or the formula should be like uploaded/(uploaded+remaining) ?

https://github.com/tus/TUSKit/blob/7901b99a2c923756c8d41300f40cf70572555c9f/Example/TUSKit/ViewController.swift#L94

**Comment by Acconut** [comment]
> 2\. the formula should be like uploaded/(uploaded+remaining)

Good catch, I think this option is correct indeed.

**Comment by tjeerdintveen** [comment]
Yeah I think you're right.  And besides that, there is more ambiguity when uploading (e.g. what do you count as the start, complete start or a resumed start? What if you add files while uploading? etc. 

In the new upcoming version I document it here:
https://github.com/tus/TUSKit/blob/rewrite%2Fstart/Sources/TUSKit/TUSClient.swift#L25

**Comment by tjeerdintveen** [comment]
I looked, the behavior is correct but the naming is wrong.

`bytesRemaining` is actually the total bytes. 
https://github.com/tus/TUSKit/blob/master/TUSKit/Classes/TUSClient.swift#L334

I could rename the parameter, but that would cause a small minor migration. Instead I'd recommend to use the updated client if that's okay.  Please let me know if this is alright with you.

**Comment by avbikk** [comment]
TUSClientDelegate is perfectly fine, thank you for the explanation!
