### ISSUE TITLE
Query - Can i upload the 10gb file using TUS in post method.

### ISSUE THREAD

**Issue by dj4385** [tus/TUSKit#117]
How can i upload the more than 10gb video fill to server by REST API Post method using TUS library?

**Comment by tjeerdintveen** [comment]
Hi the 3.0.0 pull request uses FileHandle which supports large files. I haven't tried 10gb but you can try it for your use-case. Let me know if you need any help!

**Comment by dj4385** [comment]
Hello according to stackoverflow:
https://stackoverflow.com/questions/2880722/can-http-post-be-limitless#:~:text=The%20POST%20method%20itself%20does,on%20the%20size%20of%20data

Browser have some limited memories around 5gb. Let me check upload using TUS library on demo. Is it work on not.

**Comment by tjeerdintveen** [comment]
I also realized that we do copy files locally so that we can continue uploading (regardless of the original file was temporary or not). But for extremely large files we may need to support a "do not copy" flag.  But let me know how the demo goes!

**Comment by donnywals** [comment]
Hi, I just ran a test with a 10Gb file to ensure it uploads fine. I’ve tested with chunks of 100Mb and the upload completed perfectly fine. I’m closing this issue for now.
