### ISSUE TITLE
How get upload link?

### ISSUE THREAD

**Issue by TDMNS** [tus/TUSKit#118]
Hey! Eight days ago I used your library, I put the emphasis on the eight, since the release 3.0.0 was released 7 days ago.
I'm having a problem getting a link to an object to load.
Should it be received after executing the TUSClient.shared.createOrResume(forUpload: uploadObject) method, in the field uploadObject.uploadLocationURL?
The link is visible in the console, but the uploadObject.uploadLocationURL field itself is always nil at any given time.

**Comment by Acconut** [comment]
Maybe @elvirion can help. Otherwise I would ask you to upgrade to v3 since we are not able to support earlier versions anymore.

**Comment by elvirion** [comment]
Hi @TDMNS, I've joined @ 3.0.0, so I'm afraid I can't help with versions before that. With 3.0.0 you can add the url to the context which you'll receive back, per task (UUID), when you call `start` on the client.
