### ISSUE TITLE
Chunk size updation.

### ISSUE THREAD

**Issue by Deepak3097** [tus/TUSKit#119]
Hi,
Is there anyway we can update the Chunk size without making changes in the library?? @Acconut

**Comment by Deepak3097** [comment]
@Acconut @elvirion

**Comment by elvirion** [comment]
Hi @Deepak3097,

At the moment it's not possible to update the chunkSize. However, we could look into adding this as an argument in the `TUSClient` initializer with the current `chunkSize` as a default value. Would that help?

**Comment by Deepak3097** [comment]
HI @elvirion , 
Yes that would help as well.

**Comment by elvirion** [comment]
@Deepak3097 I've just merged the change https://github.com/tus/TUSKit/pull/121

After I've added your request of https://github.com/tus/TUSKit/issues/120 I will make the new release ;). I expect to release within 1-2 weeks

**Comment by elvirion** [comment]
Hi @Deepak3097, I've released 3.1.1 that includes your request.
