### ISSUE TITLE
ERROR Unsupported URL

### ISSUE THREAD

**Issue by makoy21** [tus/TUSKit#12]
Hi Im getting this error while uploading.

I'am using iphone 5 v9.2.1.

<TUSResumableUpload.m:(151)> ERROR: connection did fail due to: Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x17d758a0 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL}}, NSLocalizedDescription=unsupported URL}

error: Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x17d758a0 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL}}, NSLocalizedDescription=unsupported URL}

**Comment by MMasterson** [comment]
Hey @makoy21, I'm happy to help resolve this for you. I just a little more information,

Can you supply some code of your TUSKit initialization and upload function?
What URL are you uploading to? 
What version of the tus protocol are you using? 
Which library of the server are you using? 
Is the iPhone 5 the only platform you've tested it on?
Do you have any other clients successfully uploading to the server?

**Comment by makoy21** [comment]
Hi @MMasterson 
**TUSKit initialization**
```
TUSResumableUpload *upload = [[TUSResumableUpload alloc] initWithURL:[UPLOAD_ENDPOINT stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding] data:uploadData fingerprint:fingerprint];

 [Self. assetLibrary assetForURL: assetUrl resultBlock: ^ (ALAsset* asset) {
 NSString *fingerprint = [assetUrl absoluteString];
 TUSAssetData *uploadData = [[TUSAssetData alloc] initWithAsset:asset];

      upload.progressBlock = ^(NSInteger bytesWritten, NSInteger bytesTotal){
            // Update your progress bar here
            NSLog(@"progress: %d / %d", bytesWritten, bytesTotal);
        };
        
        upload.resultBlock = ^(NSURL* fileURL){
            // Use the upload url
            NSLog(@"url: %@", fileURL);
        };
        
        upload.failureBlock = ^(NSError* error){
            // Handle the error
            NSLog(@"error: %@", error);
        };
      [upload start];
```

What URL are you uploading to?
I am using my custom TUS Server in AWS

**What version of the tus protocol are you using? **
TUS 1.0.0

**Which library of the server are you using? **
This one https://github.com/tus/tus-node-server/

**Is the iPhone 5 the only platform you've tested it on?**
No I also use iTouch gen 5

**Do you have any other clients successfully uploading to the server?**
Yes on android and it's working fine

**Comment by Acconut** [comment]
@makoy21 Thank you for this input. However, we would be pleased if you could tell us the exact URL as it stored in `UPLOAD_ENDPOINT`. We suspect that the URL might have an incorrect format, such as the missing `http://` protocol, and therefore causes the "unsupported URL" error.

**Comment by makoy21** [comment]
@Acconut 
`static NSString* const UPLOAD_ENDPOINT = @"http://sample-tus-server.com/files/";`

**Comment by MMasterson** [comment]
@makoy21 what exactly is `http://sample-tus-server.com`? - After pinging it, I've discovered there is nothing at that address - that's why it is unsupported. Replace` http://sample-tus-server.com` with the address to the server hosting your tus instance

**Comment by MMasterson** [comment]
Hey @makoy21 - I will be closing the issue since `http://sample-tus-server.com` is an invalid server. If you run into this problem after setting up your `tus` server, feel free to reopen the issue, or post any other issues you may have and I'll be happy to help!

Mark
