### ISSUE TITLE
Cancelling a single upload

### ISSUE THREAD

**Issue by Deepak3097** [tus/TUSKit#120]
Hi, 
In the latest release of TUS, i cannot see an option to cancel a single upload data. `stopAndCancelAll` -> This cancels all ongoing uploads.

**Comment by Deepak3097** [comment]
@Acconut @elvirion

**Comment by elvirion** [comment]
Hi @Deepak3097,

That's correct. At the moment there's no option to cancel a single upload. I will look into adding this soon. As a work around you can call `stopAndCancellAll` then `removeCacheFor(id:)` which removes the file and metadata for the specified task (uuid) and then call `start` to continue the remaining uploads.

Hope that helps

**Comment by Deepak3097** [comment]
Hi @elvirion, 
Actually the workaround suggested can lead to more issues at our end because we have pause/cancel of single uploads implemented. And restarting all the remaining uploads can start uploads that were paused on user action as well.

Having a mechanism to pause/cancel single uploads and resuming single uploads could really help.

**Comment by elvirion** [comment]
Hi @Deepak3097,

Thanks for your quick response. I understand your problem and I will look into it soon and get back to you asap.

**Comment by Deepak3097** [comment]
Thank you @elvirion, and it would really help if you could tell me when the next release would be available??

**Comment by elvirion** [comment]
Hi @Deepak3097, I've released 3.1.1 that includes your request.
