### ISSUE TITLE
How to use this library Objective-C project?

### ISSUE THREAD

**Issue by luzianscherrer** [tus/TUSKit#123]
I'm trying to use this library in a Objective-C project but I haven't managed to get it working. Could you please help me out what exactly to ```@import``` or ```#import```? Do I need to generate bridging headers?

**Comment by Acconut** [comment]
TUSKit is not usable for Objective-C right now, but only from Swift. We currently do not have plans to provide an API for Objective-C, unfortunately. You would have to build your own bridge. Sorry for that.
