### ISSUE TITLE
Background URL session support

### ISSUE THREAD

**Issue by foxware00** [tus/TUSKit#128]
I see we've got a new version using background support in iOS 13 and higher. However you cannot use background url sessions, something of a requirement if you're starting uploading in a share extension and then picking up where you left off in the main app.

Some of the old issues which were resolved, but have since been re-opened due to the recent 3.0.0 changes

https://github.com/tus/TUSKit/issues/57#issuecomment-610188074

Do you think we could move back to delegates rather than callbacks to allow for both background sessions and background tasks side by side?

Many thanks

**Comment by donnywals** [comment]
Hi @foxware00, we’re currently in the process of exploring this 👍🏼

**Comment by Acconut** [comment]
We are still actively working on background uploads. I am going to close this issue as it is similar to https://github.com/tus/TUSKit/issues/127.
