### ISSUE TITLE
I got an Error Unsupported URL

### ISSUE THREAD

**Issue by dio1677a** [tus/TUSKit#13]
Hi I got an error when uploading
I use iPhone6S Plus ,iOS9.3.2
this is my error message:
Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL, NSUnderlyingError=0x126aa11b0 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL}}}

my url:  http://211.78.245.94:1080

**Comment by Acconut** [comment]
From looking at the similar issue in tus-android-client (https://github.com/tus/tus-android-client/issues/6) would suggest using the proper upload creation URL http://211.78.245.94:1080/files/ (instead of http://211.78.245.94:1080/ which is missing the required path). However, I may be wrong since I am no iOS developer :) Please give it a try and report back.

**Comment by dio1677a** [comment]
Hi ,I replace the url ,but ,I got the same error

error: Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL, NSUnderlyingError=0x127ed2ba0 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL}}}

**Comment by MMasterson** [comment]
@dio1677a - are you still having trouble with the setup? I'll be taking a look into today and updating a few of the operations.

**Comment by dio1677a** [comment]
My colleague had upload successfully via android by the same url
my url is : http://211.78.245.94:1080/files/

**Comment by Acconut** [comment]
@dio1677a Does the log contain information regarding TUSKit's activity? If so, please post it here.

**Comment by dio1677a** [comment]
Hi, I got the infomation from log
"2016-04-18 10:13:42.131 TucIOTest[224:3707] <TUSResumableUpload.m:(62)> No resumable upload URL for fingerprint assets-library://asset/asset.PNG?id=3CA06F6C-7F2A-4D83-9913-1A1BADA5673F&ext=PNG
2016-04-18 10:13:42.166 TucIOTest[224:3707] <TUSData.m:(98)> TUSData stream opened
2016-04-18 10:13:42.167 TucIOTest[224:3707] <TUSData.m:(115)> Reading 32768 bytes from 0 to 32768 until 352230
2016-04-18 10:13:42.332 TucIOTest[224:3707] <TUSResumableUpload.m:(207)> Created resumable upload at (null) for fingerprint assets-library://asset/asset.PNG?id=3CA06F6C-7F2A-4D83-9913-1A1BADA5673F&ext=PNG
2016-04-18 10:13:42.339 TucIOTest[224:3707] <TUSResumableUpload.m:(127)> Resuming upload at (null) for fingerprint assets-library://asset/asset.PNG?id=3CA06F6C-7F2A-4D83-9913-1A1BADA5673F&ext=PNG from offset 0
2016-04-18 10:13:42.340 TucIOTest[224:3707] <TUSResumableUpload.m:(141)> ERROR: connection did fail due to: Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL, NSUnderlyingError=0x136a49340 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL}}}
2016-04-18 10:13:42.341 TucIOTest[224:3707] error: Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL, NSUnderlyingError=0x136a49340 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL}}}"

**Comment by kvz** [comment]
I might be missing the point here as I'm just dropping by, but `assets-library://asset/asset.PNG` doesn't appear like a URL/protocol that we support?

**Comment by Acconut** [comment]
@dio1677a Thank you a lot for this snippet. I assume this will help us a lot.
As it seems, TUSKit is unable to extract the upload's URL (from the Location header) after creating an upload. This causes the URL to be null which results in the "unsupported URL" error.

@MMasterson Could it be that we are missing the necessary steps to verify the response of a POST request in terms of status code and the existence of the Location header (https://github.com/tus/TUSKit/blob/master/Pod/Classes/TUSResumableUpload.m#L244)? Somehow the tus server returns a non-2XX status code without the Location header which is the root of this chain reaction.

> @kvz: I might be missing the point here as I'm just dropping by, but assets-library://asset/asset.PNG doesn't appear like a URL/protocol that we support?

I do not think so. This is actually the internal URL for an asset file included in @dio1677a's application. See it as a similar thing as the `file:///` URLs.

**Comment by kvz** [comment]
Ah okay, never mind me!

**Comment by MMasterson** [comment]
@dio1677a @Acconut I'm currently looking into the issue. Seems like there is some faulty communication.

**Comment by dio1677a** [comment]
thanks a lot

**Comment by MMasterson** [comment]
@dio1677a quick update

The server is responding with a 301 (redirect) and when it's redirecting it is losing the POST portion. I am working on a fix, should be done pretty soon.

But I also noticed, you not using the correct initializer...

`        TUSResumableUpload *upload = [[TUSResumableUpload alloc] initWithURL:[UPLOAD_ENDPOINT stringByAddingPercentEncodingWithAllowedCharacters:[NSCharacterSet URLQueryAllowedCharacterSet]] data:uploadData fingerprint:fingerprint];`
Has been depreciated.

` TUSResumableUpload *upload = [[TUSResumableUpload alloc] initWithURL:UPLOAD_ENDPOINT data:uploadData fingerprint:fingerprint uploadHeaders:headers fileName:@"name.png"];`

Are you sure you are using tus 1.0.0 and the most up to date pod?

**Comment by dio1677a** [comment]
Hi
From my pods, "Using TUSKit (1.0.0)",but the initializer was 
```
- (id)initWithURL:(NSString *)url
              data:(TUSData *)data
       fingerprint:(NSString *)fingerprint;
```
I had try to update pod 10 min ago ,but still got the old initializer

**Comment by MMasterson** [comment]
@dio1677a  should be good to go!
