### ISSUE TITLE
Chunksize and filesize. How to set using older objective c framework?

### ISSUE THREAD

**Issue by pangia** [tus/TUSKit#130]
I am using the older objective C version of the framework (version 1.4.2). Everything works fine, except the videos are getting uploaded and staying in a false 'ReadyToStream' status. The duration is set to zero in the response, but the dimensions are correct.

Also, the thumbnail is available.. just no video.

I noticed in the javascript package that there is an 'options' object that gets populated with filesize and chunk size, as well as the endpoint to our server. Is there a place I can set this in the objc package? Thank you :)

**Comment by Acconut** [comment]
Chunk size can be set using this method: https://github.com/tus/TUSKit/blob/907be6f7096ce4abd1a157e250e177004d9231d9/TUSKit/TUSResumableUpload.m#L257

The upload size cannot be changed and is set automatically based on the input data: https://github.com/tus/TUSKit/blob/1.4.2/TUSKit/TUSResumableUpload.m#L294

Hope this helps!
