### ISSUE TITLE
Uploading to Vimeo Error [couldNotCreateFileOnServer]

### ISSUE THREAD

**Issue by KKyosuke** [tus/TUSKit#133]
When trying to upload to viemo [this function](https://github.com/tus/TUSKit/blob/master/Sources/TUSKit/TUSAPI.swift#L76-L93) returns the exception and the upload fails.

It seems the vimeo server does not allow the POST method and does not return the location field.

How should I solve this problem?
1. ask vimeo to enable POST and return "location" field
2. [skip the check and return upload url](https://github.com/Lacicu/TUSKit/blob/master/Sources/TUSKit/TUSAPI.swift#L76-L82)

**Comment by BradPatras** [comment]
I just ran into this as well.  Vimeo doesn't support the __Creation__ tus protocol extension, while TUSKit is currently assuming the server supports it.

I think TUSKit should be doing what the tus protocol [documentation](https://tus.io/protocols/resumable-upload.html) suggests and not assuming the server will support the creation protocol extension: 
> Feature detection SHOULD be achieved by the Client sending an OPTIONS request and the Server responding with the Tus-Extension header

**Comment by Acconut** [comment]
@KKyosuke, I think @BradPatras answered your question (thank you), so I will close this. Let us know if you need more assistance
