### ISSUE TITLE
Why does TUSKit assume the server supports the CreationTask?

### ISSUE THREAD

**Issue by BradPatras** [tus/TUSKit#134]
According to [tus.io](https://tus.io/protocols/resumable-upload.html), the work that is currently being done in the CreationTask is an extension and not part of the core tus protocol which means it isn't required to be supported by tus servers. I don't think TUSKit should be assuming the server supports it or at least fail gracefully and attempt the upload with the given server url.

Here's the quote from the tus protocol:
>Clients and Servers are encouraged to implement as many of the extensions as possible. Feature detection SHOULD be achieved by the Client sending an OPTIONS request and the Server responding with the Tus-Extension header.

The specific API i'm trying to work with is Vimeo's video upload API.  It doesn't appear that they support the Creation protocol according to their documentation: [Using the resumable approach](https://developer.vimeo.com/api/upload/videos#resumable-approach).  They basically require the clients to do the creation step manually, not in the way specified in the tus protocol.

**Comment by BradPatras** [comment]
I found a [comment](https://github.com/tus/TUSKit/issues/68#issuecomment-623389258) in issue #68 that mentions a way to skip the creation step but it looks like that function is no longer available.

**Comment by BradPatras** [comment]
i'd love to submit a PR but even a quick fix might have some gotchas involved.  
The quick and dirty fix that I just successfully implemented on my fork involves adding a `var enableCreation: Bool` flag on `TUSClient`.  Then updating [TUSClient.swift#makeMetadata()](https://github.com/tus/TUSKit/blob/60cbc639ddd66158558c6fd7e28b89456f61f366/Sources/TUSKit/TUSClient.swift#L337) to take that flag into consideration will cause the creation step to be skipped. 

Something like this:
```swift
func makeMetadata() throws -> UploadMetadata {
  let size = try getSize()
  let url = uploadURL ?? serverURL
  
  let metadata = UploadMetadata(id: id, filePath: filePath, uploadURL: url, size: size, customHeaders: customHeaders, mimeType: filePath.mimeType.nonEmpty, context: context)
  
  if !enableCreation {
    metadata.remoteDestination = url
  }
  
  return metadata
}
``` 

The gotcha is that `TUSAPI.swift` will still send up the `Upload-Extension: creation` header in all the requests.

**Comment by gurpreetKobe** [comment]
Hi @BradPatras . I am trying to upload images (single and multiple) but every time I seem to get "couldNotCreateFileOnServer" error. The android version seems to be working fine. Both of us are using the same backend server. Can you guide me on this or share a working example as I read in a thread you were also probably facing a similar issue?

**Comment by BradPatras** [comment]
@gurpreetKobe Try switching your dependency to my fork of TUSKit and pass in an empty array for the TUSClient initializer param, `supportedExtensions`. If this fixes your problem, then you're probably hitting the same issue as me.

**Comment by gurpreetKobe** [comment]
@BradPatras  Thanks for thw quick reponse. I tried but did not work. I am able to upload on "https://tusd.tusdemo.net/files" (provided in the example) but not on my team's backend server. :/

**Comment by BradPatras** [comment]
@gurpreetKobe bummer, you might be dealing with a different problem then 🫤

**Comment by fmp6475** [comment]
Hi @BradPatras Thanks for the sharing of this quick fix. It took me one step further implementing upload feature using Vimeo and tus protocol. 
However I got another error: `TUSKit.TUSClientError.couldNotGetFileStatus`. Do you have any idea what am I missing? 

Here's my code snippet:
```
do {      
    try tusClient = TUSClient(server: URL(string: "api.vimeo.com")!, sessionIdentifier: "VIMEO", storageDirectory: URL(string: "VIMEO"))
    tusClient?.delegate = self
    try tusClient?.uploadFileAt(filePath: videoURL,  // File URL at local: file:///var/mobile/Containers/Data/Application/B09xxxx/Documents/movie.mov
                                uploadURL: URL(string: response.upload.upload_link),   // Return from Vimeo: https://asia-files.tus.vimeo.com/files/vimeo-prod-src-tus-asia/e003xxxxxxxxx
                                customHeaders: ["Tus-Resumable": "1.0.0", 
                                                "Upload-Offset": "0", 
                                                "Content-Type": "application/offset+octet-stream", 
                                                "Accept": "application/vnd.vimeo.*+json;version=3.4"])
} catch {
    print("TUS upload error")
}
```

**Comment by BradPatras** [comment]
@fmp6475 A couple things, you shouldn't have to add the custom headers, "Tus-Resumable", "Upload-Offset", or "Content-Type" since those will be added by TUSKit automatically.

I haven't used the `uploadFileAt` version of the upload, so I'd verify that the file exists where you expect it to, or you could also try using the other version of the upload function (which I have used successfully), `upload(data: ...` (the TUSClient will cache the data into local storage for you)

**Comment by fmp6475** [comment]
@BradPatras Thanks for your suggestions! After removing the custom headers, it worked. No further error occurred 👍

**Comment by Acconut** [comment]
@BradPatras Thanks for your help! I will close this since I think your PR #137 resolves this shortcoming.
