### ISSUE TITLE
 The operation couldn’t be completed. (TUSKit.TUSClientError error 7.)

### ISSUE THREAD

**Issue by Shivam-becker** [tus/TUSKit#136]
Error coming when uploading image from swift client to dotnet client

**Comment by tursunovic** [comment]
Hi @Shivam-becker,

Could you provide more context regarding your issue (e.g. TUSKit version, platform etc)? And can you reproduce it every-time?

**Comment by Shivam-becker** [comment]
The operation couldn’t be completed. (TUSKit.TUSClientError error 7.)
Hi @tursunovic . Thanks for your quick reply. Yes it's reproducing everytime. It's working fine with android but not iOS. I am using TUSKit pod Version 3.1.2 Xcode Version 13.0  using Swift 5. 
This is how I'm initializing. Calling this method in viewDidLoad : - 
  func initialiseTUSClient() {
        do {
            tusClient = try TUSClient(server: URL(string: "https://0b37-122-160-69-90.in.ngrok.io/uploads")!, sessionIdentifier: "Axle")
            tusClient?.delegate = self
            tusClient?.start()
        }
        catch {
            Debugger.sharedInstance.printToConsole(message: "Error: Could not intialise TUS Client")
        }
    } 

This is what I'm calling on button action :- 

   let imageAsset = self.selectedImagesAssetsArray.first?.asset //PHAsset
            PHImageManager.default().requestImage(for: imageAsset!, targetSize: self.assetThumbnailSize, contentMode: .aspectFill, options: nil, resultHandler: {(result, info)in
                if result != nil {
                    do {
                        let imageDataJpeg = result!.jpegData(compressionQuality: 0.7)
                        let imgDataBase64 = imageDataJpeg!.base64EncodedData()
                         try self.tusClient?.upload(data: imgDataBase64, customHeaders: ["filetype":".jpeg"])
                    }
                    catch {
                        Debugger.sharedInstance.printToConsole(message: "Unable to upload.Inside Catch Block")
                    }
                    
                }
            })


Here is server configuration , We are using Dotnet core 6.0 as backend (tusdotnet client 2.6.0)

app.Use((context, next) =>
{
    context.Features.Get<IHttpMaxRequestBodySizeFeature>().MaxRequestBodySize = null;
    return next.Invoke();
});

app.Use(async (httpContext, next) =>
{
   var requestTimeout = TimeSpan.FromSeconds(60);
    using var timeoutCts = CancellationTokenSource.CreateLinkedTokenSource(httpContext.RequestAborted);
timeoutCts.CancelAfter(requestTimeout);

httpContext.RequestAborted = timeoutCts.Token;

    await next();
});


app.UseTus(httpContext => new DefaultTusConfiguration
{
Store = new TusDiskStore("wwwroot/uploads/chunkData"),
    UrlPath = "/uploads",
    MetadataParsingStrategy = MetadataParsingStrategy.AllowEmptyValues,
    Expiration = new AbsoluteExpiration(TimeSpan.FromMinutes(5)),

    Events = new Events
    {
        OnFileCompleteAsync = async eventContext =>
        {

            ITusFile file = await eventContext.GetFileAsync();
            if (file != null)
            {


                //Get upload file=
                var metadata = await file.GetMetadataAsync(eventContext.CancellationToken);

                //Get the target file name in the above file metadata
                var fileNameMetadata = metadata.ContainsKey("filename") ? metadata["filename"] : metadata["name"];

                //The target file name is encoded in Base64, so it needs to be decoded here
                var fileName = fileNameMetadata.GetString(Encoding.UTF8);

                var extensionName = Path.GetExtension(fileName);
$"{eventContext.FileId}{extensionName}"));
                File.Move(Path.Combine("wwwroot/uploads/chunkData", eventContext.FileId), Path.Combine("wwwroot/uploads/", $"{eventContext.FileId},{extensionName}"));
                File.Delete(Path.Combine("wwwroot/uploads/chunkData", $"{eventContext.FileId}.chunkstart"));
                File.Delete(Path.Combine("wwwroot/uploads/chunkData", $"{eventContext.FileId}.chunkcomplete"));
                File.Delete(Path.Combine("wwwroot/uploads/chunkData", $"{eventContext.FileId}.uploadlength"));
                File.Delete(Path.Combine("wwwroot/uploads/chunkData", $"{eventContext.FileId}.metadata"));
            }
        }
    }
});

**Comment by tursunovic** [comment]
Hi @Shivam-becker,

Your initialisation and usage of the TUSClient seems to be fine. However, the "TUSKit.TUSClientError error 7." looks like a `couldNotCreateFileOnServer` error, which is [triggered](https://github.com/tus/TUSKit/blob/60cbc639ddd66158558c6fd7e28b89456f61f366/Sources/TUSKit/Tasks/CreationTask.swift#L70) when the creation request fails. 

Can you indicate if your server supports the [Creation](https://tus.io/protocols/resumable-upload.html#protocol-extensions) extension, or just the [Core](https://tus.io/protocols/resumable-upload.html#core-protocol) protocol?

**Comment by Shivam-becker** [comment]
i have added custom header (upload-metadata:filetype asdtiytasd76sa7d67as6dahsd==,contenttype sdgakhsgd==)

than problem solved

**Comment by Shivam-becker** [comment]
fIXED
