### ISSUE TITLE
Error when compiling with just published XCode 14 RC.

### ISSUE THREAD

**Issue by genkernel** [tus/TUSKit#139]
Apple just released next major version of XCode and their XCode Cloud now defaults to XCode 14.
When building TUSKit using XCode 14 build fails with an error:

<img width="1296" alt="Screen Shot 2022-09-08 at 12 15 41 🌙" src="https://user-images.githubusercontent.com/1649419/189207359-eed33fe9-5f1b-472d-a4f4-fc3775864f26.png">

Would maintainers like to update library themselves or potentially interested in having me making a pull request?

Related context:
https://stackoverflow.com/a/51250282

Environment:
XCode 14 RC
swift-driver version: 1.62.8 Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)

**Comment by tursunovic** [comment]
Hi @genkernel,

For now, you can use the [xcode14](https://github.com/tus/TUSKit/tree/xcode14) branch. It will be merged in the coming days.

**Comment by genkernel** [comment]
Ahh I didn't not notice the branch. Thanks!
