### ISSUE TITLE
Improve background uploading

### ISSUE THREAD

**Issue by cjhenck** [tus/TUSKit#14]
For large and resumable uploads it makes sense for TUSKit to support background uploads.

It seems like there should be a way to do this with NSURLSession.

**Comment by MMasterson** [comment]
I've received this feedback before. Working on an update that will support this, should only be a few more days :)

**Comment by cjhenck** [comment]
That's great!  I was about to start working on it myself depending on feedback 😉

**Comment by MMasterson** [comment]
Let me know if this update is suffice for you!

**Comment by cjhenck** [comment]
While this is helpful, this isn't actually what I meant.  My concern was that if the application is put into the background, the uploads will stop.  However, many users may expect uploads to continue unsupervised (e.g. start uploading a video, then go read your email):

https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html#//apple_ref/doc/uid/TP40007072-CH4-SW5

**Comment by MMasterson** [comment]
Oh I see what the original concern was, so you didn't mean off the main thread - just meant app-background uploads.

This seems like it would have to be be very heavily integrated into the app that is being developed. 

You can always try the upload of the when it hit's background and it will resume. The protocol is written to not restart an upload but continue the upload from its last place. It should be pretty simple to integrate the app. But not sure of a good way to implement it into the SDK. Without just adding it into the example app.

Do you have any suggestions?

**Comment by cjhenck** [comment]
Not at the moment, I am working on it this week though so I will let you know if I come up with a good method.

**Comment by MMasterson** [comment]
@cjhenck AFNetworking seems to be a solid fit for your problem from what I've been reading - do you have any thoughts on it? I'd like to come up with a perfect solution for background uploads

**Comment by cjhenck** [comment]
I'm pretty sure that even with AFNetworking (which is a great library) we have to use background NSURLSessions.  The problem that I've encountered is that if there is a wire failure, iOS will automatically retry an upload request you place onto the session, which will then continue to fail (and be cut off by the server) because the offset remains at 0 (or its last value if there was a successful chunk).  Basically there is no way to use NSURLSession unless we time out uploads after a very short period of time (so iOS will not retry for that long) _or_ we chunk the file in advance into small parts and support a reset extension.

You can see the work that we completed before discovering that there are no callbacks for wire failures [here](https://github.com/Findyr/TUSKit/tree/NSURLSession_Upload).

Linking to the reset proposal https://github.com/tus/tus-resumable-upload-protocol/issues/82

**Comment by cjhenck** [comment]
There is one workaround that may be functional for most people: subscribe to location changes, and do a quick HEAD and then PATCH request as a long-running task.  It will eventually get killed by the OS, but will at least move the upload along whenever the user changes location.  It seems like DropBox may use this technique.

**Comment by Acconut** [comment]
> @cjhenck: There is one workaround that may be functional for most people: subscribe to location changes, and do a quick HEAD and then PATCH request as a long-running task. It will eventually get killed by the OS, but will at least move the upload along whenever the user changes location. It seems like DropBox may use this technique.

This is an interesting approach but I can imagine it brings a few disadvantages with it. For example, does "subscribing to location changes" require the user to enable GPS or allow the application to even read the current position such as Android does? I could also believe that this behavior may not be optimal for battery lifetime.

You may also be interested in my suggestion over here: https://github.com/tus/tus-resumable-upload-protocol/issues/82#issuecomment-223952698

**Comment by MMasterson** [comment]
@cjhenck I am not fully opposed to your idea. Although I am not 100% sold on making it a full feature due to the fact that location services must be enabled and I wanna keep the SDK lite and heavy on battery/cpu/etc ussage. I can see it as an additional optional feature or we can go down the other alternative path that @Acconut suggested.


Which would benefit you more @cjhenck?

**Comment by cjhenck** [comment]
@MMasterson I like the solution that @Acconut put forward.  

I think that for the location-based resume, it's not something to build in, just something that users could be informed of as a solution.  The big change needed is persisting the data between app reloads, which we may not even want to do.  

As an aside, I'm not sure I see that the current TUSKit implementation will change the offset of the TUSData object if you resume a failed upload.

**Comment by RobIsHere** [comment]
Hi! Is there any progress on getting the ios support done right?
Can we already build on the implementation in the PR? Or is there still work to do?

I would really like to pack this in a cordova plugin and use it for our uploads. But we have huge files and TUSkit will fail in its current state. Workaround: the user touches his phone every minute for about an hour :grin:

**Comment by MMasterson** [comment]
@RobIsHere - The PR was merged :) The pod isn't updated, so you'll have to install it manually until the new Pod is out

**Comment by cjhenck** [comment]
@RobIsHere with the updated version, the uploads will continue in the background for a period (until iOS stops the process).  If you'd like to restart them occasionally, you can listen for significant location changes and restart the uploads then.

**Comment by MMasterson** [comment]
@RobIsHere I'll be finishing up some docs for the new features before full release - unless @cjhenck already has some

**Comment by cjhenck** [comment]
@MMasterson alas no documentation yet!

**Comment by RobIsHere** [comment]
Thank you very much! Amazing!

I have read all the threads regarding this, but I'm not sure about the exact features that are currently in it. As i understood you had to chunk the files in TUSKit, queue up the fragments with the ios NSUrlSession, build them together when the upload is finished.

So from user perspective:
- keeps running in lock screen and when checking mails etc
- ios retries uploading the fragments on itself

Did i understand it right?

What i didn't understand was the need for location update. Was it because you need the app to run from time to time to do admin work? or is this solved and the discussion is obsolete?

**Comment by MMasterson** [comment]
@RobIsHere The discussion lead to an update where an upload is done in the background and continues as a background task until iOS will stop the process after a certain period of time. There are now better implementations to restart the upload and keep track of it.

The Location Update is more of a pattern, than an actual feature. If you implement location services on the iOS app, and listen for signification location changes (or non signification, depending on your needs) you may wish to re-try to resume the upload automatically in case iOS has stopped the process so the upload can still continue in the background.

For example a user uploads a video, but has low to medium internet connectivity or it is a very large file, the upload will take a while. The upload continues when the user goes to another app, etc. But now it's been a while and the upload is still going, and iOS has terminated the upload. If your app is listening to location changes, and you run a resume uploads call on movement, the upload will continue.

**Comment by Acconut** [comment]
@MMasterson The so called Creation With Upload extension will soon be part of the tus specification (https://github.com/tus/tus-resumable-upload-protocol/pull/88). Also, I implemented the first draft of it into tusd, so you may want to play around with it

**Comment by RobIsHere** [comment]
Ok. Got it! Thanks for the detailed explanation!

**Comment by allappsmobile** [comment]
@MMasterson  was this resolved? (without using location/audio trick) we are experiencing the same issue, upload does not resume after app going to background and os terminating process... anyhelp?

**Comment by MMasterson** [comment]
@allappsmobile The location trick is the only work around at this time because iOS itself does the suspending of long requests.

**Comment by tribitinfotech** [comment]
hello,

When i select Large video TUS kit automatically start from initial bytes in progressBlock after uploading few bytes

Can you please let me know why this happens in TUS Kit iOS ?

Thanks

**Comment by cjhenck** [comment]
@tribitinfotech I'm not entirely sure I understand.  Are those bytes definitely upload bytes and not the initial HEAD/POST request?  Are those initial bytes appearing on the server side?  It's possible you are receiving an error code causing the reset.  The best way to check would be to add a debug point at the exit of the first request to see what the error status was. Can you please open a new issue?

**Comment by cjhenck** [comment]
See #30 for continued discussion
