### ISSUE TITLE
[!] Unable to read the license file `LICENSE` for the spec `TUSKit (3.1.4)`

### ISSUE THREAD

**Issue by yunustek** [tus/TUSKit#141]
Pod install taking this warning:

> [!] Unable to read the license file `LICENSE` for the spec `TUSKit (3.1.4)``

**Comment by Acconut** [comment]
Thank you for notifying us. Is this just a warning or preventing you from installing TUSKit?

**Comment by yunustek** [comment]
Thank you too! This is only a warning ⚠️

**Comment by m3t8d1tr** [comment]
Why didn't you add the license file?

**Comment by tursunovic** [comment]
Hi @m3t8d1tr,

I've just added the license, will be included in next release.

**Comment by yunustek** [comment]
Any plan for next release?

**Comment by Acconut** [comment]
Yes, we will be publishing a release as soon as possible, hopefully in the next two weeks.

**Comment by Acconut** [comment]
Just to let you know that we publish TUSKit 3.1.5 some time ago: https://github.com/tus/TUSKit/tree/3.1.5
