### ISSUE TITLE
Extra space in Upload-Metadata encoding

### ISSUE THREAD

**Issue by razvanDev27** [tus/TUSKit#147]
When I try to upload a video I get this error

"Header Upload-Metadata: The Upload-Metadata request and response header MUST consist of one or more comma - separated key - value pairs. The key and value MUST be separated by a space.The key MUST NOT contain spaces and commas and MUST NOT be empty. The key SHOULD be ASCII encoded and the value MUST be Base64 encoded. All keys MUST be unique. The value MAY be empty. In these cases, the space, which would normally separate the key and the value, MAY be left out."

After debugging I found that in `TUSAPI.swift` at line 124 there is `str += ", "`, changing that to `str += ","` fixes the issue for me.

However I had to download the library, add it to the project and fix it locally.

**Comment by andreaslindahl** [comment]
I've got the same problem

**Comment by andreaslindahl** [comment]
I have the same problem

**Comment by andreaslindahl** [comment]
Is there a fix for this bug, which does not require downloading the library and making changes to it?

**Comment by andreaslindahl** [comment]
Are there any plans to fix this issue? Can't upgrade to the latest version until this is fixed...

**Comment by Acconut** [comment]
We hope to address this in the next weeks.

@andreaslindahl or @razvanDev27, would you be able to open a PR for this? Then we can merge and release it quicker.

**Comment by andreaslindahl** [comment]
There's now a PR with this fix #151

**Comment by donnywals** [comment]
I’ve merged your PR, we’ll have a release out with this fix in the next couple of days. Thanks a tonne for the help!
