### ISSUE TITLE
How to use this in kotlin multiplatform 

### ISSUE THREAD

**Issue by bestMechanic** [tus/TUSKit#148]
Is there any way this can be used inside a kotlin multiplatform project?

**Comment by Acconut** [comment]
I have no experience with Kotlin multiplatform, but I am not sure if you could use this library.

From their docs: https://kotlinlang.org/docs/native-objc-interop.html

> A Swift library can be used in Kotlin code if its API is exported to Objective-C with @objc. Pure Swift modules are not yet supported.

TUSKit is entirely written in Swift without any Objective-C remaining, so I think we do not meet this requirement.

**Comment by Acconut** [comment]
Closing this for now. Let us know if you want to continue the discussion.
