### ISSUE TITLE
SSL Pinning Task [Swift]

### ISSUE THREAD

**Issue by jeffcampbelldev** [tus/TUSKit#149]
Is the SSL Pinning task done?
How can I upload data over "HTTPS" request as it failed uploading with the "401" status code
@MMasterson

**Comment by Acconut** [comment]
I am not expert at this, but maybe you are able to provide your own URLSession to https://github.com/tus/TUSKit/blob/27628506549de45c0590d195e69027f5156bfe3b/Sources/TUSKit/TUSAPI.swift#L37, which is configured with the pinning certificate as mentioned in https://medium.com/trendyol-tech/securing-ios-applications-with-ssl-pinning-38d551945306.
