### ISSUE TITLE
Get metadata for a failed uploads

### ISSUE THREAD

**Issue by kiyosoft** [tus/TUSKit#155]
With the current implementation there is a way to find `failedUploadIds()`, but there is no way to access all failed uploads with their metadata

I can see that the `tusClient.start()` method gives the upload ids with their respective metadata, but in my use case I want the metadata without starting the uploads

**Comment by Acconut** [comment]
tus-js-client has a method `findPreviousUploads` which retrieves a list of started uploads based on information stored on the local devices: https://github.com/tus/tus-js-client/blob/main/docs/api.md#tusuploadfindpreviousuploads This also includes the metadata of each upload. Maybe something similar would be sense for each tus client, including TUSKit.

**Comment by kiyosoft** [comment]
@Acconut I can create a PR for this

**Comment by donnywals** [comment]
That would be good @kiyosoft, this sounds like a useful addition for the SDK

**Comment by Acconut** [comment]
Implemented in #156.
