### ISSUE TITLE
POST requests include unknown `Upload-Extension` header

### ISSUE THREAD

**Issue by Acconut** [tus/TUSKit#164]
POST request for creating uploads include the `Upload-Extension: creation` header field. While it might make sense to include such information, it is not part of the protocol specification and nowhere used, as far as I know. Hence, I think we should remove this header field.

See https://github.com/search?q=repo%3Atus%2FTUSKit%20Upload-Extension&type=code

Here is also the request as seen in Wireshark:

<img width="727" alt="image" src="https://github.com/tus/TUSKit/assets/1375043/8a4f3e56-4d02-4b8e-987c-4cfc2a0e5524">

**Comment by BradPatras** [comment]
I think you're right, I can get a PR up to remove this.
