### ISSUE TITLE
Cannot resume a failed upload unless you know the server offset

### ISSUE THREAD

**Issue by cjhenck** [tus/TUSKit#17]
In the current version of TUSKit, if you resume a failed upload, the TUSData is not automatically advanced to the offset received by the server when checking the file.

**Comment by kvz** [comment]
Should we indicate why this was closed? Just to leave a paper-trail for people stumbling upon this issue?

**Comment by MMasterson** [comment]
@Kvz will do, my apologies - was going to but lost time with the docs.
