### ISSUE TITLE
Ambiguity around the `retry(id:)` function

### ISSUE THREAD

**Issue by BradPatras** [tus/TUSKit#173]
The documentation for the `retry(id: UUID) -> Bool` function is seemingly misleading (or just incomplete maybe). 

It states that it `Returns: True if the id is found. False if it's not found`. 
My interpretation of that was that if I attempt to retry an upload and get `false` back from that function, I should treat that upload as permanently failed and no longer accessible because TUSKit no longer has it in it's storage.

But if I call `getStoredUploadInfo()` I can see that TUSKit is in fact still storing an upload matching that UUID... So I'm confused as to the state of my upload if TUSKit is storing it but at the same time, according to TUSKit, my upload is `"not found"`

For context, the workflow i'm currently playing with is having uploads in progress, then switching the phone to airplane mode for a few seconds and then after connection has been reestablished, calling "retry" on any UUIDs that are returned from the `failedUploadIDs()` function.

**Comment by BradPatras** [comment]
I just read through the discussions in #169 and #172. That will likely resolve this issue.

**Comment by donnywals** [comment]
Closing this in favor of further chat in the PR
