### ISSUE TITLE
Scheduler Crash in TUSClient.cancel(id:)

### ISSUE THREAD

**Issue by BradPatras** [tus/TUSKit#176]
This is a tough one, but I'm seeing a crash that I can't personally reproduce happening when calling `TUSClient.cancel`.

The error also has a message attached: `BUG IN CLIENT OF LIBDISPATCH: dispatch_sync called on queue already owned by current thread`

I've gotten reports in iOS 15, 16, and iPadOS 16. TUSKit versions 3.1.4 and 3.2.0.

```
Crashed: com.TUSKit.Scheduler
0  libdispatch.dylib              0x11b4c __DISPATCH_WAIT_FOR_QUEUE__ + 452
1  libdispatch.dylib              0x116ec _dispatch_sync_f_slow + 140
2  libswiftDispatch.dylib         0x2084 implicit closure #2 in implicit closure #1 in OS_dispatch_queue.sync<A>(execute:) + 152
3  libswiftDispatch.dylib         0x1460 partial apply for implicit closure #2 in implicit closure #1 in OS_dispatch_queue.sync<A>(execute:) + 40
4  libswiftDispatch.dylib         0x1dfc OS_dispatch_queue._syncHelper<A>(fn:execute:rescue:) + 252
5  libswiftDispatch.dylib         0x14f0 OS_dispatch_queue.sync<A>(execute:) + 136
6  CompanyName                   0x1785a20 TUSClient.cancel(id:) + 36 (Scheduler.swift:36)
7  CompanyName                   0x179aac4 VimeoClient.cancelUpload(_:) + 109 (VimeoClient.swift:109)
8  CompanyName                   0x1817770 specialized static VideosService.processFailedUpload(client:id:onError:) + 157 (VideosService.swift:157)
9  CompanyName                   0x1817a3c specialized static VideosService.handleClientError(client:error:id:onError:) + 73 (VideosService.swift:73)
10 CompanyName                   0x179c058 protocol witness for TUSClientDelegate.uploadFailed(id:error:context:client:) in conformance VimeoClient + 186 (VimeoClient.swift:186)
11 CompanyName                   0x17891f0 TUSClient.onError(error:task:scheduler:) + 676 (TUSClient.swift:676)
12 CompanyName                   0x177a3e8 closure #1 in closure #1 in closure #1 in Scheduler.checkProcessNextTask() + 121 (Scheduler.swift:121)
13 CompanyName                   0x1792994 thunk for @escaping @callee_guaranteed () -> () + 3493208 (<compiler-generated>:3493208)
14 libdispatch.dylib              0x637a8 _dispatch_call_block_and_release + 24
15 libdispatch.dylib              0x64780 _dispatch_client_callout + 16
16 libdispatch.dylib              0xa298 _dispatch_lane_serial_drain$VARIANT$mp + 644
17 libdispatch.dylib              0xad70 _dispatch_lane_invoke$VARIANT$mp + 396
18 libdispatch.dylib              0x14dc8 _dispatch_workloop_worker_thread + 632
19 libsystem_pthread.dylib        0x1bd0 _pthread_wqthread + 284
20 libsystem_pthread.dylib        0x1720 start_wqthread + 8
```
Taking a closer look at the stack trace, it appears as though the crashing call to `TUSClient.cancel` is made from the `TUSClientDelegate` function `uploadFailed(id: UUID, ...)`.  

Is it possible there's some threading issue with this call stack, `TUSClient.onError` -> `TUSClientDelegate.uploadFailed` -> `TUSClient.cancel`?

Has anyone else ever come across this?

**Comment by donnywals** [comment]
I can't say that I've seen this one before but I'll take a look at it. The information you've provided seems enough to at least do some basic investigation

**Comment by BradPatras** [comment]
I'm still seeing this issue unfortunately. I'm considering just trying to wrap the call to `TUSClient.cancel` in a main queue dispatch.

**Comment by donnywals** [comment]
That's probably worth a shot. 

Are there any particular steps you follow to get a consistent repro on this? I did take a look but didn't see anything that stood out as an obvious cause at the time. if you have any further input I will happily take it

**Comment by BradPatras** [comment]
I haven't figured out how to reproduce it either but i'll keep looking into it.

**Comment by BradPatras** [comment]
Following up on this, I deployed a tentative fix and it seems to have worked.  All I did was dispatch to the main queue in the TUSClientDelegate functions before calling back into any TUSClient functions.

```swift
public func uploadFailed(id: UUID, error: Error, context: [String: String]?, client: TUSKit.TUSClient) {
  DispatchQueue.main.async {
    // codepath that may call into TUSClient.cancel(id:)
  }
}
```
