### ISSUE TITLE
Renaming TUSKit

### ISSUE THREAD

**Issue by kvz** [tus/TUSKit#19]
Is that desired? What would be a better name? @cjhenck @MMasterson

**Comment by cjhenck** [comment]
I personally think TUSKit is a pretty good name - not sure I can come up with something better unless it were very generic (like the java client). The problem with a generic name is I'm not sure how you encompass that it is both iOS and macOS.

**Comment by MMasterson** [comment]
I don't think it's a necisary change at the moment, I'd like to get it more up to par before renaming. Such as closing the remaining issues, creating an macOS example.

But for renaming purposes, i don't see why tus-Apple-client wouldn't work.

**Comment by kvz** [comment]
Alright, let's think about it some more, closing this in the meantime. If we ever feel stronger we can revisit 👍 

(i personally don't have an opinion, only brought this up as i heard some complaints about this earlier, but i'm a little out of my comfort-zone naming ios/macos things)
