### ISSUE TITLE
Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL"

### ISSUE THREAD

**Issue by PhilipHayes** [tus/TUSKit#22]
I'm running the sample code exactly as it appears in the repo and one thing I've noticed in the errors that it logs back is that it somehow clips the http: off the the beginning of the url. 

I'm running 1.2.1

my input (ip replaced with 0.0.0.0)
//static NSString* const UPLOAD_ENDPOINT = @"http://0.0.0.0:8000/files/";

2016-09-13 12:38:02.662 TUSKit[1201:675510] <TUSResumableUpload.m:(335)> Created resumable upload at **_//0.0.0.0:8000/files/7b829af661dfafd516e252d3689e99ba_** for id 293CA199-A87E-46E9-9ED5-479B91E7123B
2016-09-13 12:38:02.683 TUSKit[1201:675510] <TUSResumableUpload.m:(470)> Resuming upload to //0.0.0.0:8000/files/7b829af661dfafd516e252d3689e99ba with id 293CA199-A87E-46E9-9ED5-479B91E7123B from offset 0
2016-09-13 12:38:02.686 TUSKit[1201:675510] <TUSData.m:(112)> TUSData stream opened
2016-09-13 12:38:02.686 TUSKit[1201:675510] <TUSData.m:(129)> Reading 32768 bytes from 0 to 32768 until 13732856
2016-09-13 12:38:02.690 TUSKit[1201:675510] <TUSResumableUpload.m:(496)> Error or no response during attempt to upload file, checking state
2016-09-13 12:38:02.711 TUSKit[1201:675510] <TUSResumableUpload.m:(397)> Unrecoverable error during attempt to check file
2016-09-13 12:38:02.719 TUSKit[1201:675510] error: Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x159c32960 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}, NSErrorFailingURLStringKey=//0.0.0.0:8000/files/7b829af661dfafd516e252d3689e99ba, NSErrorFailingURLKey=//0.0.0.0:8000/files/7b829af661dfafd516e252d3689e99ba, NSLocalizedDescription=unsupported URL}

**Comment by MMasterson** [comment]
@PhilipHayes I'm AFK until later on in the day. Will check when I get back. In the meantime can you supply the actual code? Also if this is time sensitive, have your tried 1.3? The Example file should help you out with implementing that.

**Comment by PhilipHayes** [comment]
//
//  TKViewController.m
//  TUSKit
//
//  Created by Michael Avila on 08/10/2014.
//  Copyright (c) 2014 Michael Avila. All rights reserved.
//
//  Additions and changes for TUSSession implementation by Findyr
//  Copyright (c) 2016 Findyr

#import "TKViewController.h"

#import <AssetsLibrary/AssetsLibrary.h>
#import <TUSKit/TUSKit.h>

static NSString* const UPLOAD_ENDPOINT = @"http://162.208.48.211:8000/files/";
static NSString* const FILE_NAME = @"tuskit_example";

@interface TKViewController ()

@property (strong,nonatomic) ALAssetsLibrary *assetLibrary;
@property (strong, nonatomic) TUSSession *tusSession;

@end

static TUSUploadProgressBlock progressBlock = ^(int64_t bytesWritten, int64_t bytesTotal){
    // Update your progress bar here
    NSLog(@"progress: %llu / %llu", (unsigned long long)bytesWritten, (unsigned long long)bytesTotal);
};

static TUSUploadResultBlock resultBlock = ^(NSURL* fileURL){
    // Use the upload url
    NSLog(@"url: %@", fileURL);
};

static TUSUploadFailureBlock failureBlock = ^(NSError* error){
    // Handle the error
    NSLog(@"error: %@", error);
};

@implementation TKViewController

-(void)viewDidLoad
{
    NSURL * applicationSupportURL = [[[NSFileManager defaultManager] URLsForDirectory:NSApplicationSupportDirectory inDomains:NSUserDomainMask] firstObject];
    
    TUSUploadStore * uploadStore = [[TUSFileUploadStore alloc] initWithURL:[applicationSupportURL URLByAppendingPathComponent:FILE_NAME]];
    self.tusSession = [[TUSSession alloc] initWithEndpoint:[[NSURL alloc] initWithString:UPLOAD_ENDPOINT] dataStore:uploadStore allowsCellularAccess:YES];
    for (TUSResumableUpload * upload in [self.tusSession restoreAllUploads]){
        upload.progressBlock = progressBlock;
        upload.resultBlock = resultBlock;
        upload.failureBlock = failureBlock;
    }
    [self.tusSession resumeAll];
}

- (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    [self selectFile:nil];
}

- (IBAction)selectFile:(id)sender {
    UIImagePickerController *imagePicker = [UIImagePickerController new];
    imagePicker.mediaTypes = [UIImagePickerController availableMediaTypesForSourceType:imagePicker.sourceType];
    imagePicker.delegate = self;
    [self presentViewController:imagePicker animated:YES completion:nil];
}

- (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingMediaWithInfo:(NSDictionary *)info {
    [self dismissViewControllerAnimated:YES completion:nil];
    NSURL *assetUrl = [info valueForKey:UIImagePickerControllerReferenceURL];
    
    if (!self.assetLibrary) {
        self.assetLibrary = [ALAssetsLibrary new];
    }
    
    [self.assetLibrary assetForURL:assetUrl resultBlock:^(ALAsset* asset) {

        
        ALAssetRepresentation *rep = [asset defaultRepresentation];
        Byte *buffer = (Byte*)malloc(rep.size);
        NSUInteger buffered = [rep getBytes:buffer fromOffset:0.0 length:rep.size error:nil];
        
        NSData *data = [NSData dataWithBytesNoCopy:buffer length:buffered freeWhenDone:YES];
        NSURL *documentDirectory = [[NSFileManager defaultManager] URLsForDirectory:NSDocumentDirectory inDomains:NSAllDomainsMask][0];
        NSURL *fileUrl = [documentDirectory URLByAppendingPathComponent:[[NSUUID alloc] init].UUIDString];
        
        NSError *error;
        if (![data writeToURL:fileUrl options:NSDataWritingAtomic error:&error]) {
            NSLog(@"%li", (long)error.code);
        }
        
        
        // Initiate the background transfer
        TUSResumableUpload *upload = [self.tusSession createUploadFromFile:fileUrl headers:@{} metadata:@{}];

        upload.progressBlock = progressBlock;
        upload.resultBlock = resultBlock;
        upload.failureBlock = failureBlock;

        [upload resume];
    } failureBlock:^(NSError* error) {
        NSLog(@"Unable to load asset due to: %@", error);
    }];
}

@end

**Comment by cjhenck** [comment]
@PhilipHayes I'll take a look now.  Out of curiosity, did you enable arbitrary loads in your app? In iOS 9+, insecure http doesn't work in apps without either enabling arbitrary domains or whitelisting specific domains and the error messages can be cryptic.

**Comment by PhilipHayes** [comment]
Yes its enabled.

**Comment by PhilipHayes** [comment]
I'll take a look at the 1.3.0 version in the mean time. 

For more information, on the server side there is indeed an established connection, but however the upload cancels leaving only a placeholder file on the server.

**Comment by MMasterson** [comment]
@PhilipHayes you are not using the correct implementation. TUSFileUploadStore does not exist in 1.2.x.

https://github.com/tus/TUSKit/releases/tag/1.2.1 this is the release including the correct Example file.

And the docs on the readme show the correct way to use 1.2.x.

**Comment by PhilipHayes** [comment]
Heh you are correct, sorry for the wrong version number!

**Comment by MMasterson** [comment]
1.2.1's example implementation is as follows. For 1.3 @cjhenck would be more of a help. And be sure you are using the cloning the repo and including the class files. 1.3 has not been released on the Pod yet.

```
- (IBAction)selectFile:(id)sender {
    UIImagePickerController *imagePicker = [UIImagePickerController new];
    imagePicker.mediaTypes = [UIImagePickerController availableMediaTypesForSourceType:imagePicker.sourceType];
    imagePicker.delegate = self;
    [self presentViewController:imagePicker animated:YES completion:nil];
}

- (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingMediaWithInfo:(NSDictionary *)info {
    [self dismissViewControllerAnimated:YES completion:nil];
    NSURL *assetUrl = [info valueForKey:UIImagePickerControllerReferenceURL];
    
    if (!self.assetLibrary) {
        self.assetLibrary = [ALAssetsLibrary new];
    }
    
    [self.assetLibrary assetForURL:assetUrl resultBlock:^(ALAsset* asset) {
        NSString *fingerprint = [assetUrl absoluteString];
        NSDictionary *headers =  @{@"":@""};
        
        TUSAssetData *uploadData = [[TUSAssetData alloc] initWithAsset:asset];
        TUSResumableUpload *upload = [[TUSResumableUpload alloc] initWithURL:UPLOAD_ENDPOINT data:uploadData fingerprint:fingerprint uploadHeaders:headers fileName:@"video.mp4"];

        upload.progressBlock = ^(NSInteger bytesWritten, NSInteger bytesTotal){
           // Update your progress bar here
           NSLog(@"progress: %d / %d", bytesWritten, bytesTotal);
        };

        upload.resultBlock = ^(NSURL* fileURL){
           // Use the upload url
           NSLog(@"url: %@", fileURL);
        };

        upload.failureBlock = ^(NSError* error){
           // Handle the error
           NSLog(@"error: %@", error);
        };

        [upload start];
    } failureBlock:^(NSError* error) {
        NSLog(@"Unable to load asset due to: %@", error);
    }];
}
```

**Comment by PhilipHayes** [comment]
You got it.

**Comment by cjhenck** [comment]
@MMasterson :+1:

**Comment by PhilipHayes** [comment]
Okay so using the same url but now I'm getting a connection lost error using the sample code you provided above. 

    static NSString* const UPLOAD_ENDPOINT = @"http://162.208.48.211:8000/files";



    - (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    [self selectFile:nil];
    }

    - (IBAction)selectFile:(id)sender {
        UIImagePickerController *imagePicker = [UIImagePickerController new];
        imagePicker.mediaTypes = [UIImagePickerController availableMediaTypesForSourceType:imagePicker.sourceType];
        imagePicker.delegate = self;
        [self presentViewController:imagePicker animated:YES completion:nil];
    }

    - (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingMediaWithInfo:(NSDictionary *)info {
    [self dismissViewControllerAnimated:YES completion:nil];
    NSURL *assetUrl = [info valueForKey:UIImagePickerControllerReferenceURL];
    
    if (!self.assetLibrary) {
        self.assetLibrary = [ALAssetsLibrary new];
    }
    
    [self.assetLibrary assetForURL:assetUrl resultBlock:^(ALAsset* asset) {
        NSString *fingerprint = [assetUrl absoluteString];
        NSDictionary *headers =  @{@"":@""};
        
        TUSAssetData *uploadData = [[TUSAssetData alloc] initWithAsset:asset];
        TUSResumableUpload *upload = [[TUSResumableUpload alloc] initWithURL:UPLOAD_ENDPOINT data:uploadData fingerprint:fingerprint uploadHeaders:headers fileName:@"video.mp4"];

        upload.progressBlock = ^(NSInteger bytesWritten, NSInteger bytesTotal){
           // Update your progress bar here
           NSLog(@"progress: %d / %d", bytesWritten, bytesTotal);
        };

        upload.resultBlock = ^(NSURL* fileURL){
           // Use the upload url
           NSLog(@"url: %@", fileURL);
        };

        upload.failureBlock = ^(NSError* error){
           // Handle the error
           NSLog(@"error: %@", error);
        };

        [upload start];
    } failureBlock:^(NSError* error) {
        NSLog(@"Unable to load asset due to: %@", error);
    }];
    }

2016-09-13 14:35:58.081 TUSKit[1231:699636] progress: 0 / 0
2016-09-13 14:35:58.082 TUSKit[1231:699636] <TUSResumableUpload.m:(78)> No resumable upload URL for fingerprint assets-library://asset/asset.MOV?id=A70D5A73-819C-40ED-8A8A-D748F1271973&ext=MOV
2016-09-13 14:35:58.086 TUSKit[1231:699636] <TUSData.m:(101)> TUSData stream opened
2016-09-13 14:35:58.087 TUSKit[1231:699636] <TUSData.m:(118)> Reading 32768 bytes from 0 to 32768 until 13732856
2016-09-13 14:35:58.284 TUSKit[1231:699833] <TUSResumableUpload.m:(207)> ERROR: connection did fail due to: Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo={NSUnderlyingError=0x161321a90 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "The network connection was lost." UserInfo={NSErrorFailingURLStringKey=http://162.208.48.211:8000/files, NSErrorFailingURLKey=http://162.208.48.211:8000/files, _kCFStreamErrorCodeKey=-4, _kCFStreamErrorDomainKey=4, NSLocalizedDescription=The network connection was lost.}}, NSErrorFailingURLStringKey=http://162.208.48.211:8000/files, NSErrorFailingURLKey=http://162.208.48.211:8000/files, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-4, NSLocalizedDescription=The network connection was lost.}
2016-09-13 14:35:58.285 TUSKit[1231:699833] error: Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo={NSUnderlyingError=0x161321a90 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "The network connection was lost." UserInfo={NSErrorFailingURLStringKey=http://162.208.48.211:8000/files, NSErrorFailingURLKey=http://162.208.48.211:8000/files, _kCFStreamErrorCodeKey=-4, _kCFStreamErrorDomainKey=4, NSLocalizedDescription=The network connection was lost.}}, NSErrorFailingURLStringKey=http://162.208.48.211:8000/files, NSErrorFailingURLKey=http://162.208.48.211:8000/files, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-4, NSLocalizedDescription=The network connection was lost.}

**Comment by PhilipHayes** [comment]
Allow arbitrary loads is also enabled here as well.

**Comment by PhilipHayes** [comment]
This looks to be similar to the issue #13

I'm also able to ping it like done so in issue #12

**Comment by PhilipHayes** [comment]
I'm using the nodejs server 1.0.0, I've tried on localhost, my outbound ip, and my own vps. I was a lot farther with 1.3.0's example than I am with 1.2.1's example it seems.

**Comment by PhilipHayes** [comment]
Okay I got it to work in 1.3.0, but the error code -1002 is the issue, the url is being truncated accidentally. Repairing the url fixes everything and it works quite nicely. However I'd rather not have to repair the url. I'll try and find where it is being truncated.

**Comment by PhilipHayes** [comment]
The issue is not in the iOS client but in the nodejs posthandler.js

https://github.com/tus/tus-node-server/blob/master/lib/handlers/PostHandler.js at line 18

the protocol is missing, and so the response comes back invalid, yet pointing to an actual asset.

**Comment by PhilipHayes** [comment]
In TUSResumableUpload.m I changed at line 331 from 

    NSString *location = [httpResponse.allHeaderFields valueForKey:HTTP_LOCATION];
    weakself.uploadUrl = [NSURL URLWithString:location];

to 

    NSString *fileName = [[httpResponse.allHeaderFields valueForKey:HTTP_LOCATION] componentsSeparatedByString:@"/"].lastObject;

    NSString *destination = self.delegate.createUploadURL.absoluteString;

    NSString *location = [NSString stringWithFormat:@"%@%@", destination, fileName];

    weakself.uploadUrl = [NSURL URLWithString: location];

and it works

**Comment by MMasterson** [comment]
Thanks for the PR @PhilipHayes - my only question is really for @cjhenck. Did you run into this problem as well with 1.3? Maybe patched it before I merged?

**Comment by MMasterson** [comment]
Solved with latest commit. discussed in https://github.com/tus/TUSKit/pull/23
