### ISSUE TITLE
How to add TUSKit to project objective-c XCode 6.3?

### ISSUE THREAD

**Issue by paneaktae** [tus/TUSKit#25]
Help me please when i try to add project have many issues.

**Comment by MMasterson** [comment]
In order to add TUSKit to such a low development platform, you'll need to download the repo as a  ZIP and drag over the Classes folder then import TUSKit in order to use it. The CocoaPod isn't supported for targets that low.

Can you explain "many issues"? What issues are you having?

**Comment by MMasterson** [comment]
@paneaktae gonna close the issue. let me know if you need anymore help and I'll reopen it!

**Comment by tgreco** [comment]
@MMasterson how would you add this to an objective C library? #import "TUSKit.h" fails to work.
