### ISSUE TITLE
Any plans for swift 3 migrations ?

### ISSUE THREAD

**Issue by tahseen0amin** [tus/TUSKit#26]
Any plans for swift 3 migration ?

**Comment by MMasterson** [comment]
Hey @tahseen0amin - this SDK is written in objective-c and should work for all swift versions. Is there a specific issue you're hitting? A swift wrapper for the SDK is on its way, and will be written in Swift 3.1.

**Comment by tahseen0amin** [comment]
No issue so far.
I am migrating code from objective C to swift 3 and was thinking of writing a swift wrapper myself if no one is doing it. Glad to know things have already started.
