### ISSUE TITLE
Uploading video file using example demo doesn't resume after connection lost.

### ISSUE THREAD

**Issue by gjanblaszczyk** [tus/TUSKit#27]
In the current version of TUSKit and example demo, if you uploading the video file and you lost the network connection for a few seconds and then network appered again then resume upload procedure will try to resending the file forever cusing huge memory leaking and app crash.
I tested with official tus demo server: "https://master.tus.io/files/"

    2017-04-19 11:36:21.806 TUSKit[3178:132189] progress: 245760 / 2604768
    2017-04-19 11:36:51.908 TUSKit[3178:132189] <TUSResumableUpload.m:(500)> Error or no     response during attempt to upload file, checking state
    2017-04-19 11:37:22.234 TUSKit[3178:132189] <TUSResumableUpload.m:(416)> Error or no response during attempt to check file, retrying
    2017-04-19 11:37:33.217 TUSKit[3178:132189] <TUSResumableUpload.m:(555)> Resumable upload at https://master.tus.io/files/35f62600f83473960a3c7e8675ac3dfc for 843F3DEC-792C-4693-A1EA- 1AF2F0BC339D from 204800 (204800)
    2017-04-19 11:37:33.219 TUSKit[3178:132189] <TUSResumableUpload.m:(474)> Resuming upload to https://master.tus.io/files/35f62600f83473960a3c7e8675ac3dfc with id 843F3DEC-792C-4693-A1EA-1AF2F0BC339D from offset 204800 <--------It's trying to resume forever cusing app to crash!!!!

**Comment by MMasterson** [comment]
I'll take a look later tonight - are you using strictly the example project? or do you have any other code implementations you're working off of?

**Comment by gjanblaszczyk** [comment]
Hi MMasterson,

Yes, I am using strictly the example project. The only change I made was url to the server endpoint to "https://master.tus.io/files/". I run this on iOS 10.3 under the leatest  Xcode 8.3. If you will have some problems with reproducing this issue then just give me a shout and I will record the short screencast to show you what I see...

**Comment by dilawer** [comment]
Hi @MMasterson do you have any update on it ?

Thanks

**Comment by allappsmobile** [comment]
Hi anyone found a solution for this??  
@MMasterson @gjanblaszczyk  Any input greatly appreciated!

**Comment by MMasterson** [comment]
@gjanblaszczyk @dilawer @allappsmobile haven't yet found a fix yet - anyone have any luck on this issue? Would love some of your feedback.

**Comment by gjanblaszczyk** [comment]
Not me because I didn't use tusd server. I drop it and I am using custom server implementation that it works without this issue.

**Comment by MMasterson** [comment]
Strange.

What implementation SDK are you using @gjanblaszczyk?

@kvz this issue only seems to be present with a `tusd` implementation. Any reason you can think of why there's a miss step with the `tusd`?

**Comment by Acconut** [comment]
> this issue only seems to be present with a tusd implementation. Any reason you can think of why there's a miss step with the tusd?

Can't think of any. Are you sure that this is a problem with tusd? We have been using it in production for some time now and didn't experience such problems. Did you try it with another server, such as tus-node-server, yet?

**Comment by Acconut** [comment]
It may also be helpful to define what the actual issue is. From the logs, @gjanblaszczyk posted, I can't see where it should end up in an endless loop.

**Comment by gjanblaszczyk** [comment]
Hi @MMasterson , I am planning to close this issue if no one else experiencing this issue. I guess that can be problem specific to my environment. Does anyone else see this problem? if not I will close this issue shortly...

**Comment by MMasterson** [comment]
Will reopen if anyone else experiences this issue.

**Comment by kvz** [comment]
cc @elvirion

**Comment by elvirion** [comment]
@tomgreco which version are you using?

**Comment by tomgreco** [comment]
@elvirion the latest version.
