### ISSUE TITLE
Not able to Upload large file

### ISSUE THREAD

**Issue by tribitinfotech** [tus/TUSKit#30]
Hello,

I have implemented TUSKit successfully in code with swift 4 and xcode 9 and videos are uploaded successfully as well.

Problem that i am facing is if i select large videos and start to upload it will started upload video but after uploading few bytes (80%) it will start to upload again from 0 bytes in progress block thus it will not uploaded fully video

Can you please suggest why this happens with large video ?

Thanks

**Comment by cjhenck** [comment]
I haven't experienced the same problem myself except when the server is offline or hasn't saved the file.  
What's your server configuration? 
Have you checked whether the initial bytes end up saved on the server?
Can you add a debug point at the error code for the upload to see why it failed, and at the HEAD request of the resumption to see what the response is?

**Comment by tribitinfotech** [comment]
Thanks for your reply cjhenk

Actually i am using same server provided by TUSKit (http://master.tus.io/files/) and fileURL of my local document library.

As per your instruction i have put debug point to see errors and it stated status code 413 (request too large) 

Hope this much is enough for information

Thanks

**Comment by kvz** [comment]
`413 (request too large)` might actually be something that Nginx returns which is proxying in front of tus at the demo server. @Acconut does this sound plausible?

**Comment by tribitinfotech** [comment]
Hello,

Let me provide you full error description and for your information i am not getting this type of error everytime.Will getting this at only some time and for few minutes only then it works automatically

<TUSResumableUpload.m:(534)> Invalid status code (413) during attempt to upload, checking state

![screen shot 2017-10-04 at 2 35 37 pm](https://user-images.githubusercontent.com/20172434/31173744-6c143344-a911-11e7-9468-c7ff6fedf17e.png)

**Comment by Acconut** [comment]
> 413 (request too large) might actually be something that Nginx returns which is proxying in front of tusd at the demo server. @Acconut does this sound plausible?

No, I don't think that it's Nginx' fault. The tusd instance at master.tus.io has an upload size limit of 1GB since it's just a demo server and not meant for production use. If this limit is exceeded a 413 will be returned. @tribitinfotech How big is the video you are uploading?

**Comment by tribitinfotech** [comment]
Video is small around 8-10 sec but issue is this happens only for few minutes after that if you upload same video it works perfectly

Thanks

**Comment by Acconut** [comment]
Sorry, if I was unclear. I was referring to the file size in bytes not the length of the video. How big is the video in terms of file size in bytes?

**Comment by phawk** [comment]
@Acconut I am having issues with large files as well. I have been using the JavaScript TUS client for some time with a chunk size set to 5MB and using tus-ruby-server behind nginx. Now using TUSKit I get errors uploading videos of > 100mb because my nginx max upload size is only 100mb. 

Having read the source code (I am a swift programmer so my objective-c is a little lacking) it doesn't look like there is any support for chunked uploads, or am I missing anything?

P.s. also had some trouble using TUSKit with macOS, I'll have to submit a PR soon.

Thanks!

**Comment by Acconut** [comment]
> Having read the source code (I am a swift programmer so my objective-c is a little lacking) it doesn't look like there is any support for chunked uploads, or am I missing anything?

I don't know that out of my head, but @MMasterson will know for sure as he is the genius behind TUSKit.

> P.s. also had some trouble using TUSKit with macOS, I'll have to submit a PR soon.

Amazing, thank you for that in advance 👍

**Comment by fadielse** [comment]
i have the same problem if upload photo with certain network example i use provider network "XL" in my country.
results that occur when the process is complete will be repeated again to 0/53058

this is the result of debugging:

progress: 53048/53048
[1777: 431297] TIC Read Status [810: 0x11dc03590]: 1:57
[1777: 431297] Task <647F81A7-9BD3-4D30-8431-8894D55FF72D>. <1576> HTTP load failed (error code: -1005 [4: -4])
[1777: 432552] Task <647F81A7-9BD3-4D30-8431-8894D55FF72D>. <1576> finished with error - code: -1005
[1777: 430502] <TUSResumableUpload.m: (517)> Error or no response during attempt to upload file, checking state
<TUSResumableUpload.m: (576)> Resumable upload at http: //upload.**************.com/files/6e9f972426b441b7ce2c53e5df119c08 for E67D55E6-AB9F-4F57-A459-5FB85588B463 from 0 (0)
[1777: 430502] <TUSResumableUpload.m: (489)> Resuming uploaded to http: //upload.************** .com / files / 6e9f972426b441b7ce2c53e5df119c08 with id E67D55E6-AB9F-4F57-A459-5FB85588B463 from offset 0
[1777: 430502] <TUSData.m: (112)> TUSData stream opened
[1777: 430502] <TUSData.m: (129)> Reading 32768 bytes from 0 to 32768 until 53048
[1777: 430502] <TUSData.m: (129)> Reading 20280 bytes from 32768 to 53048 until 53048
progress: 32768/53048
progress: 53048/53048

....... infinite loop here

But if I use the same network and use the VPN all the uploads run smoothly.

**Comment by MMasterson** [comment]
https://github.com/tus/TUSKit/pull/38 seems to solve this issue with chunking
