### ISSUE TITLE
dead?

### ISSUE THREAD

**Issue by pvinis** [tus/TUSKit#31]
is this project dead? there are many deprecated things in here.

**Comment by Acconut** [comment]
This project is not dead. Since this is a usable and working version, activity in this repository has been a bit rare but it's still supported.

> there are many deprecated things in here.

Would you mind explaining a bit more what "things" are deprecated? Are you talking about TUSKit's API or Foundation's API?

**Comment by pvinis** [comment]
deprecations as in it uses https://developer.apple.com/documentation/assetslibrary/alassetslibrary and its been deprecated since ios 9.

**Comment by MMasterson** [comment]
Not dead - But yes I have forgotten about this method, mainly because `initWithURL` is what should be used. As for the Example I will update with the new Photo Library and change the asset `init`

For future, this is a community project and PR's are always welcome! :)
