### ISSUE TITLE
TUSFileUploadStore fails to save to disk - restoreAllUploads always return empty

### ISSUE THREAD

**Issue by dongmai** [tus/TUSKit#33]
Hi everyone, 

I'm using the example for iOS, but function `[self.tusSession restoreAllUploads]` always return an empty array although I know there is pending upload for sure. (I've closed app from app switcher)

As reading code, I guess that's caused by `TUSFileUploadStore` is linking with app container absolute path while the path itself will be changed per app launching.

Any solution for this? Thanks.

**Comment by dongmai** [comment]
As debugging I saw that `TUSFileUploadStore` always failed to save upload task to disk.

The line **54** in `TUSFileUploadStore.m `file, console always got `success: 0`
<img width="730" alt="screen shot 2018-01-03 at 4 05 29 pm" src="https://user-images.githubusercontent.com/3855966/34514443-10882b26-f0a0-11e7-882e-808550227708.png">

My environment: Xcode 9.2.

**Comment by MMasterson** [comment]
Few questions for more info:
Can you please provide your full implementation? Also a little a bit about your use case? How many files are you storing, etc? and version of TUSKit are you running? Thanks!

I'll look into this in the AM, set it on my calendar

**Comment by dongmai** [comment]
I'm using exactly the source code on master branch.

What I've done is uploading multiple files under low network connection (to make sure there is always having pending uploads), then stopped and ran app again on simulator but there is no pending upload at all.

**Comment by MMasterson** [comment]
Okay got it. I'll look into the saving to disk, add a failure catch as well. Then run through to make sure the `Uploadstore` saves on app termination.

**Comment by dongmai** [comment]
Ok, thank you.

**Comment by dongmai** [comment]
Hi @MMasterson, did you find any solution for this? 
As googling I see this might useful, https://stackoverflow.com/a/8713924/1455262

**Comment by dongmai** [comment]
Oh, I did a minor update and the issue has resolved, 

On file `TUSResumableUpload.m`, line `609`, need to change `[NSNull null]` to a string.
<img width="1233" alt="screen shot 2018-01-04 at 2 55 44 pm" src="https://user-images.githubusercontent.com/3855966/34554442-8047ff94-f15f-11e7-9dd9-31fbf81883db.png">

Seems the bug is related to `serialize` function as the returned dictionary isn't a valid property list object.

**Comment by MMasterson** [comment]
I looked in a bit today, but didn't have enough time to run an update on the pod. Glad to figured out a fix, if you can submit a PR to the repo it'd be much appreciated. I plan on releasing a new version to the repo and pod this week with a few more tweaks. But if this fixes your problem, everything seems stable. I'll run a few more tests and integrate with TravisCI before release. Thank you for contribution! You can star the the repo for info on when the pod updates.

**Comment by MMasterson** [comment]
Closed issued with #34
