### ISSUE TITLE
Headers and Metadata in Swift

### ISSUE THREAD

**Issue by ilariadinardo3** [tus/TUSKit#40]
Which is the right position and name to insert "Upload-Length","Upload-Offset" and etc.? Where is their location, headers or metadata?
let upload: TUSResumableUpload = tusSession.createUpload(fromFile: fileURl, headers: ["Authorization":"Bearer " + token], metadata: ["":""])

**Comment by MMasterson** [comment]
I'm sorry, not really sure what you're asking here. Are you retying to put in your own `Upload-Offset` and `Upload-Length` headers? Those are already added by the SDK - there is no need to add them yourself

**Comment by MMasterson** [comment]
closing this issue. If you are still having issues @ilariadinardo3 feel free to comment and I'll reopen it
