### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by darecki** [tus/TUSKit#43]
Do you plan to add support for Carthage users?

Even if not, it would be great to add instructions how to install the lib manually. Not everyone uses CocoaPods. Thanks.

**Comment by MMasterson** [comment]
Hey @darecki

I can totally add Carthage support for you. I know #41 was submitted with manual lib/Carthage support in mind and it’s been on my mind since. I’ll get working on it for you

**Comment by xorander00** [comment]
Nice!  I was just wondering this myself a minute ago and then happened to stumble upon this issue.  I'll test it as soon as it's pushed up :)

**Comment by MMasterson** [comment]
@darecki @xorander00 it doesn’t seem to be too big of a task, should have this closed by the weekend.

**Comment by MMasterson** [comment]
addressed in `swift-development` check #65
