### ISSUE TITLE
Unrecognized selector exception on initWithUploadId:file:delegate:uploadHeaders:finalMetadata:state:uploadUrl:

### ISSUE THREAD

**Issue by GalCohen** [tus/TUSKit#44]
Hi all, thanks for a nice & simple library. Appreciate the work you save us from reinventing the wheel. I'm running into the follow issue: I tried to initialize a session with the createFromFileUpload...uploadUrl variant and I hit this every time. Looks like it funnels into a private designated initializer... possibly one that isn't implemented? 

2019-05-07 17:52:16.335337-0400 Arnor[11925:25862617] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[TUSResumableUpload initWithUploadId:file:delegate:uploadHeaders:finalMetadata:state:uploadUrl:]: unrecognized selector sent to instance 0x600002f9df80'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010e8291bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010d3c6735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010e847f44 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010e82ded6 ___forwarding___ + 1446
	4   CoreFoundation                      0x000000010e82fda8 _CF_forwarding_prep_0 + 120
	5   TUSKit                              0x000000010bf7e12e -[TUSResumableUpload initWithUploadId:file:delegate:uploadHeaders:metadata:uploadUrl:] + 622
	6   TUSKit                              0x000000010bf87252 -[TUSSession createUploadFromFile:headers:metadata:uploadUrl:] + 466

**Comment by MMasterson** [comment]
hey @GalCohen can you post the code of your implementation?

**Comment by GalCohen** [comment]
Thanks for the very quick response. Here's an example. I had to strip some stuff private stuff out, but it should still be enough to get idea across: 

```
func uploadVideo(fileURL: URL, uploadURL: URL, callback: @escaping (Result<URL, MyError>) -> Void) -> TUSResumableUpload? {
        guard let dataStore = TUSFileUploadStore(url: fileURL) else {
               callback(.failure(MyError("failed to create upload store"))))
            return nil
        }
        
        let session = TUSSession(endpoint: uploadURL, dataStore: dataStore, allowsCellularAccess: true)
        
        let headers = [
            kHeaderContentType: "application/offset+octet-stream",
            kHeaderAccept: kContentTypeVimeoResponse
        ]
        
        guard let upload = session.createUpload(fromFile: fileURL, headers: headers, metadata: nil, uploadUrl: uploadURL) else {
            callback(.failure(MyError("failed to create upload store"))))
            return nil
        }
        
        upload.failureBlock = { (error) in
            callback(.failure(MyError("failed to create upload store"))))
        }

        upload.resultBlock = { (fileUrl) in
            callback(.success(fileUrl))
        }

        upload.progressBlock = { (bytesWritten, bytesTotal) in
            print(bytesWritten, bytesTotal)
        }
        
        upload.stop()
        upload.resume()
 
        self.session = session
        self.uploader = upload
        
        return upload
    }
```

**Comment by MMasterson** [comment]
Be sure you're up to date and using version `1.4.0`

By the looks of your code, it seems like you are mixing up the two possible routes of implementing TUSKit. There is the more traditional way, where TUS creates the file when you start a new upload, and then am "upload only" route where the file was already previously created (see #42)

        `guard let upload = session.createUpload(fromFile: fileURL, headers: headers, metadata: nil, uploadUrl: uploadURL)`

`uploadURL` here would be the previously created file and not the upload endpoint initialized in the `TUSSession` 

You're looking for something more like

`session.createUpload(fromFile: fileURL, retry: -1, headers: headers, metadata: nil)`

**Comment by GalCohen** [comment]
To give some more context, I'm trying to upload a video to vimeo following this guide: 
https://developer.vimeo.com/api/upload/videos#resumable-approach

In there, the first step is POST to Vimeo to create the video file location. Step two is to kick off the resumable upload. Based on that it seemed to me that I should use the `session.createUpload(fromFile ... uploadUrl:)` version so that i skip the initial POST step done by the other createUpload method to create the file.

**Comment by GalCohen** [comment]
Hmm #42  is exactly my use case: POST already took place, just need to update. That's why I went with:
```
let upload = session.createUpload(fromFile: fileURL, headers: headers, metadata: nil, uploadUrl: uploadURL)
```

**Comment by MMasterson** [comment]
Ahh, I see now. #42 was added a bit later - I believe you can set the upload url to `https://api.vimeo.com/me/videos` in the `TUSSession`, and it'll take care of the post for you.

**Comment by GalCohen** [comment]
Ah. thanks! I'll give that a shot and report back. I wasn't sure if that step was a vimeo specific thing or part of the TUS protocol. Either way though, I still think there's an issue that causes this crash that may be worth looking further into.

**Comment by MMasterson** [comment]
However seems you may have found an issue with upload only so let me take a look and get a patch out for this. Then you can continue the current way you're going about it

**Comment by GalCohen** [comment]
@MMasterson  I tried forking this and taking a look at the fix myself, and I found several other concerning warnings... am i doing something wrong? wrong branch maybe? i'm on master, on xcode 10.1 and I'm seeing some pretty important stuff to address: 


![Screen Shot 2019-05-08 at 10 47 46 AM](https://user-images.githubusercontent.com/1293368/57384591-e5fea680-717e-11e9-9ee1-3ef875d13b22.png)


![Screen Shot 2019-05-08 at 10 47 56 AM](https://user-images.githubusercontent.com/1293368/57384607-eac35a80-717e-11e9-8617-d3cc7261b23d.png)

These are looking like runtime crashes waiting to happen :(

**Comment by MMasterson** [comment]
Yeah there are still a few warnings I have to clean up there, it's definitely on the todo list for me, among other things. But feel free to submit a PR if you'd like! 

I've submitted #45 to clear up your issue. Before I release the version though, are you able to checkout the develop branch?

**Comment by GalCohen** [comment]
Thanks @MMasterson that definitely addresses the crash. I'm not sure if this next part is related, but the request keeps timing out. Is there a way to extend the timeout? or maybe it's an indication of something wrong?

**Comment by GalCohen** [comment]
Was able to get around the timeout issue but setting the chunk size. However, now I keep getting the same offset back in the response... it never advances. http code 204

**Comment by GalCohen** [comment]
@MMasterson Phew! Problem solved... turns out i set the `TUSFileUploadStore`'s fileUrl to the same as the video's fileUrl, so it was writing over my video with other data. 

Your PR #45  solved my issue. 

I'm not sure how many people will make the same mistake I made. It might be worth considering added some assertion for the programmer error of setting the session's fileURL to the FileUploadStore's fileURL 😅

**Comment by MMasterson** [comment]
Awesome @GalCohen! Glad #45 closes this issue. 

> it might be worth considering added some assertion for the programmer error of setting the session's fileURL to the FileUploadStore's fileURL 😅

Not a bad idea, I'll make sure that's part of the next release. Merging #45 now and updating the pod to `1.4.1`
