### ISSUE TITLE
fail  stopupload() -> resumeUpload() 

### ISSUE THREAD

**Issue by red16035** [tus/TUSKit#47]
Hi, Thank for this library. 

stopUpload() -> resumeUpload() is not working.

my project is : 
- Deployment target 12.1 
- swift 4.2 
- upload url : https://master.tus.io/files/

test device : iphone 8 

code : 
func stopUpload() {
        upload?.stop()
}

func resumeUpload() {
    upload?.resume()
}

log message : 
2019-07-08 11:44:29.112666+0900 TAP[36537:6302131] <TUSResumableUpload.m:(620)> Resumable upload at https://master.tus.io/files/10c21f95ed62b406b5e071e1caf59bec+2k3EwRWlCXJ0Tg8c.l.vpggfVM7KdgIfKrx76zEvUbmYdu8GmKtnIzXX3F.lxkFtYZcDo39Z5ONfagxf5qvbz__fDBdZf3EQI5Cpzy64box4xLcWNs3d1rDjQWx2y4Rn for 204DFA9D-4313-4007-BA31-2EBAA19DED5B from 1024000 (1024000)
2019-07-08 11:44:29.127635+0900 TAP[36537:6302131] <TUSResumableUpload.m:(525)> Resuming upload to https://master.tus.io/files/10c21f95ed62b406b5e071e1caf59bec+2k3EwRWlCXJ0Tg8c.l.vpggfVM7KdgIfKrx76zEvUbmYdu8GmKtnIzXX3F.lxkFtYZcDo39Z5ONfagxf5qvbz__fDBdZf3EQI5Cpzy64box4xLcWNs3d1rDjQWx2y4Rn with id 204DFA9D-4313-4007-BA31-2EBAA19DED5B from offset 1024000
2019-07-08 11:45:00.126842+0900 TAP[36537:6303031] Task <D528B0F7-9033-4F04-BC80-30ACB5E7BA6B>.<4> finished with error - code: -1001
2019-07-08 11:45:00.127035+0900 TAP[36537:6302131] <TUSResumableUpload.m:(561)> Error or no response during attempt to upload file, checking state

**Comment by red16035** [comment]
full source 
------------------------------------------------------------------------

import Foundation
import UIKit
import TUSKit
import Photos

class FileUploader {
    
    var upload: TUSResumableUpload?
    var tusSession:TUSSession?
    
    private var progressBlock:TUSUploadProgressBlock?;
    private var resultBlock:TUSUploadResultBlock?;
    private var failureBlock:TUSUploadFailureBlock?;
    
    var fileUploadUrl:String = ""
    var fileUrl:URL?
    var fileName:String = "tuskit_example"
    var fileUploadUIHandle:FileUploaderUIProtocol
    var initComplete:Bool = false
    
    
    init( uploadUrl:String, uploadUIHandle:FileUploaderUIProtocol, fileName:String? ) {
        self.fileUploadUrl = uploadUrl
        self.fileUploadUIHandle = uploadUIHandle
//        self.fileName = fileName
        var uploadStore: TUSUploadStore? = nil
        
        let fileManager = FileManager.default
        if let applicationSupportURL = fileManager.urls(for: .applicationSupportDirectory, in: .userDomainMask).first {
            if( fileName != nil ){
                self.fileName = fileName!
            }
            uploadStore = TUSFileUploadStore(url: applicationSupportURL.appendingPathComponent(self.fileName))
            tusSession = TUSSession(endpoint: URL(string: fileUploadUrl)!, dataStore: uploadStore!, allowsCellularAccess: true)
            
            
            //init ui handle
            progressBlock = { bytesWritten, bytesTotal in
                // Update your progress bar here
                //        print(String(format: "progress: %llu / %llu", UInt64(bytesWritten), UInt64(bytesTotal)))
                print( "progress : \(bytesWritten) / \(bytesTotal)"  )
                uploadUIHandle.setProgress(progress: Int(bytesWritten), max: Int(bytesTotal))
            }
            
            resultBlock = { fileURL in
                // Use the upload url
                print("result uploaded url: \(fileURL)")
                uploadUIHandle.dismissProgress()
            }
            
            failureBlock =  { error in
                // Handle the error
                print("fail : \(error)")
                //uploadUIHandle.dismissProgress()
                //uploadUIHandle.showError(text: error.localizedDescription)
                uploadUIHandle.showRetryDialog(text: error.localizedDescription)
            }
            
            
            for upload in tusSession!.restoreAllUploads() {
                upload.progressBlock = progressBlock
                upload.resultBlock = resultBlock
                upload.failureBlock = failureBlock
            }
            //tusSession?.resumeAll()
            initComplete = true
        }else{
            uploadUIHandle.showError(text: "fail")
        }
        
    }
    
    
    func startUpload(fileUrl:URL) {
        // If a file has not been created yet by your TUS backend
        
        self.fileUrl = fileUrl
        fileUploadUIHandle.dismissProgress()
        fileUploadUIHandle.showUploadProgress()
//        tusSession?.cancelAll()
        upload = self.tusSession?.createUpload(fromFile: fileUrl, headers: [:], metadata: [:])
        upload?.progressBlock = self.progressBlock
        upload?.resultBlock = self.resultBlock
        upload?.failureBlock = self.failureBlock
        upload?.resume()
        
        
        
    }
    
    func stopUpload() {
        upload?.stop()
        //fileUploadUIHandle.dismissProgress()
        fileUploadUIHandle.showRetryDialog(text: "취소되었습니다. 다시 시도할까요?")
    }
    
    func resumeUpload() {
        fileUploadUIHandle.dismissProgress()
        fileUploadUIHandle.showUploadProgress()
        
        
        let uploaded = upload!.resume()
        print("upload : \(uploaded)")
    }
    
    func cancelUpload() {
        fileUploadUIHandle.dismissProgress()
        upload?.cancel()
    }
}

**Comment by MMasterson** [comment]
Hey @red16035 

I’ll take look at this first thing tomorrow!

**Comment by MMasterson** [comment]
hey @red16035 

running through a few tests under your specs, but just to be clear on the order here

1. you are start creating an upload, and starting it
2. stopping it in the middle of upload
3. trying to start it up again and it's failing out

**Comment by red16035** [comment]
Hi, @MMasterson 
That's right.
And I tried uploading with mp4 file.

the same in v1.3.x and v1.4.2.

**Comment by red16035** [comment]
I solved this problem. 

I added next code.

**upload?.setChunkSize( 1024 * 1024 )**
upload?.resume()

**Comment by MMasterson** [comment]
hey @red16035 glad you found a way for it to work, however you shouldn't have to do that. Although from your workaround I can see where the problem lies. I'll begin working on a fix and include it in the next version

**Comment by Pavan96** [comment]
Hi I am trying demo application and its working for video file(250 MB) upload. But I am not able to find the way to upload file in background mode as it uses **defaultSessionConfiguration**.  Does library has example  for **backgroundSessionConfigurationWithIdentifier**. Any help or guidance will be appreciated. Thanks for such a good library.

**Comment by MMasterson** [comment]
check #65 

Custom Session configs are added!
