### ISSUE TITLE
Compatibility with tus 1.0

### ISSUE THREAD

**Issue by Acconut** [tus/TUSKit#5]
tus 1.0 is just around the corner. I would be pleased to see this implementation being updated to support the next version. Most updates are outside the core so only minimal changes are required to maintain comparability. You can find detailed information or get feedback at the according issue tus/tus-resumable-upload-protocol#57-

**Comment by Acconut** [comment]
@michaelavila If you are not able or interested any more to update this project, I would be pleased to see this repository being moved to your private account if that's not a problem for you. Please, don't believe that we don't appreciate your work and efforts put into TUSKit but I want to avoid having an official library which is not compatible with the latest version of the protocol.

**Comment by michaelavila** [comment]
@Acconut I can start moving this towards 1.0 compatibility unless you have someone internal that you'd prefer to do the work.

**Comment by Acconut** [comment]
@michaelavila It would be awesome if you could do that. If you have any questions about the 1.0 release feel free to reach out to me. :)

**Comment by Drusy** [comment]
Hello, 
We have just used your example and changed few things just to be working with the TUS 1.0.0 protocol, would you need that work ? It's only few headers update.
Let me know. :)

**Comment by kvz** [comment]
@Drusy Thanks! @MMasterson is about to release a 1.0 compatible TUSKit today I think. If you have any improvements on top of that, it would be awesome if you could send us a PR for it!

**Comment by Drusy** [comment]
@kvz Well, I will stay aware of the coming changes and let you!

**Comment by MMasterson** [comment]
issue can be closed
