### ISSUE TITLE
is there an example for swift implementation?

### ISSUE THREAD

**Issue by Richardson12345** [tus/TUSKit#52]

**Comment by Richardson12345** [comment]
it seems like this question was brought up a year ago with someone stating that you can find the swift implementation on the development branch. If there is one, can i please get links? thanks

**Comment by MMasterson** [comment]
I'll add some examples for you @Richardson12345!

**Comment by Richardson12345** [comment]
thx

**Comment by Richardson12345** [comment]
@MMasterson  any updates for the swift example?
