### ISSUE TITLE
Upload large files > 1GB  

### ISSUE THREAD

**Issue by nikolaytsigvintsev** [tus/TUSKit#54]
Hi !

Will large file uploads > 1 GB be implemented ?

I cannot transfer a 1.5 GB file to an iPad with 1 GB free memory.

Thanks.

**Comment by MMasterson** [comment]
hey @nikolaytsigvintsev,

You're trying to upload an image from an iPad and getting an error, what error would that be? Sounds like you don't have enough space. The library copies the file to keep track of the data on upload
