### ISSUE TITLE
App will cashed during uploading in IOS

### ISSUE THREAD

**Issue by iqbalfaisal** [tus/TUSKit#58]
App will cashed during uploading in IOS
![74518652-06da0080-4f36-11ea-8787-50e17c14140d](https://user-images.githubusercontent.com/46706064/74520381-3e967780-4f39-11ea-8a2a-126be1f14553.png)

**Comment by Acconut** [comment]
Please provide the code to reproduce this. Also, this error seems to error in conjunction with https://github.com/vinzscam/react-native-tus-client. Can you clarify what you are doing?
