### ISSUE TITLE
ERROR: connection requested new body stream, which is currently not supported in example

### ISSUE THREAD

**Issue by MMasterson** [tus/TUSKit#6]
Running the example with our server setup `tus.io` compliant and we are receiving

`<TUSResumableUpload.m:(115)> Finished upload to PATH/videos/uploads/15/ for fingerprint assets-library://asset/asset.mp4?id=30C691FA-5866-4498-82CB-E95FB600BD74&ext=mp4
2015-04-07 01:46:36.397 TUSKit[207:8879] url: PATH/videos/uploads/15/
2015-04-07 01:46:36.410 TUSKit[207:8879] <TUSResumableUpload.m:(157)> ERROR: connection requested new body stream, which is currently not supported `

`- (NSInputStream *)connection:(NSURLConnection *)connection
            needNewBodyStream:(NSURLRequest *)request
{
    TUSLog(@"ERROR: connection requested new body stream, which is currently not supported");
    return nil;
}`

in `TUSResumableUpload.m`

is where we are getting the error , i'm just not sure why

the uploads on the server are started, but empty.

Any suggestions on how to fix this?

`Xcode 6.1.1`  
and
`Example Project`

**Comment by Acconut** [comment]
Thanks for reporting this issue but currently there is no developer actively maintaining this repository. I will try to contact the original authors.

**Comment by michaelavila** [comment]
I will take a look at this in a couple of hours.

**Comment by MMasterson** [comment]
@michaelavila @Acconut we actually just solved the body stream error. It was an API redirecting issue.

but we're still getting blank files

**Comment by MMasterson** [comment]
@michaelavila @Acconut 

Solved! The data is now writing to the server. We had to change the way the API received binary data in order to comply with `TUSKit` and the `tus` protocol.

Thank you for your quick responses! :+1:
