### ISSUE TITLE
Downloading data.

### ISSUE THREAD

**Issue by shravanteegala** [tus/TUSKit#61]
I need to download same as Uploading. How can download it.
please help me.

**Comment by Acconut** [comment]
You should be able to send a GET request to the upload URL and get the uploaded data back.

**Comment by MMasterson** [comment]
Are you talking about downloading a new file that you didn't upload @shravanteegala? Like a resumable file download for any file?

**Comment by shravanteegala** [comment]
yes

**Comment by MMasterson** [comment]
You can download the file you’ve uploaded with a GET as @Acconut suggested, however any other file probably wouldn’t work for a resumable file download in its current state.
