### ISSUE TITLE
Handling multiple file uploads

### ISSUE THREAD

**Issue by shravanteegala** [tus/TUSKit#62]
How to retrieve downloaded file url from completed block in swift.
plz help me.

**Comment by MMasterson** [comment]
Can you show the code you have @shravanteegala? It should be a returned parameter in the block.

**Comment by shravanteegala** [comment]
var myGlobalUrl:URL? = nil
class FileUploader: NSObject {
    
    var upload: TUSResumableUpload?
    var tusSession:TUSSession?

    private var progressBlock:TUSUploadProgressBlock?;
    private var resultBlock:TUSUploadResultBlock?;
    private var failureBlock:TUSUploadFailureBlock?;

    var fileUploadUrl:String = "http://111.93.31.14:3001/files/"
    var fileUrl:URL?
    var fileName:String = "tuskit_example"
    //var fileUploadUIHandle:FileUploaderUIProtocol
    var initComplete:Bool = false
    
    var mydownLoadComplete:Bool = false
    var myTusUploadedresultUrl :URL? = nil
 
    init( uploadUrl:String, uploadUIHandle:String, fileName:String? ) {
        super.init()
        self.fileUploadUrl = uploadUrl
         self.fileUploadUrl = "http://111.93.31.14:3001/files/"
       // self.myUrl = ""
       // self.fileUploadUIHandle = uploadUIHandle
        var uploadStore: TUSUploadStore? = nil
        var myreceiveUrl:URL? = nil
       
        
        let fileManager = FileManager.default
        if let applicationSupportURL = fileManager.urls(for: .applicationSupportDirectory, in: .userDomainMask).first {
            if( fileName != nil ){
                self.fileName = fileName!
            }
            uploadStore = TUSFileUploadStore(url: applicationSupportURL.appendingPathComponent(self.fileName))
            tusSession = TUSSession(endpoint: URL(string: fileUploadUrl)!, dataStore: uploadStore!, allowsCellularAccess: true)
            
            
            progressBlock = { bytesWritten, bytesTotal in
                print( "progress : \(bytesWritten) / \(bytesTotal)"  )
               // uploadUIHandle.setProgress(progress: Int(bytesWritten), max: Int(bytesTotal))
            }
            
           
          
            
            
            resultBlock = {  fileURL in
                // Use the upload url
                print("result uploaded url: \(fileURL)")
                myGlobalUrl = fileURL
                
              
               // uploadUIHandle.dismissProgress()
                if(fileURL.absoluteString.count != 0){
                    UserDefaults.standard.set(self.myTusUploadedresultUrl, forKey: "tusResultUrl")
                }

            
        
            }

**Comment by shravanteegala** [comment]
In this i access the result block fileUrl for saving imapath (variable) to my local db.

**Comment by MMasterson** [comment]
`fileURL` in the result block is the public uploaded file on your TUS server, if you wanna save the local file save the file you supply in the URL for `TUSFileUploadStore`. If you do some kind of editing in your TUS server after its uploaded, download the public facing URL that is supplied in the `resultBlock`

**Comment by MMasterson** [comment]
Did that help @shravanteegala? Or do you need more clarification

**Comment by shravanteegala** [comment]
yes it is help to me.
But how to upload  selected multiple files . kindly help me.

**Comment by shravanteegala** [comment]
above my problem clear Explanation is:

Explanation:
There is for loop which runs N times (selectedImages.count).
During each iteration, Tus(service) request is made.
It takes some time to response to the  downloaded response url.
This is an asynchronous method, so it doesn't block the execution (meaning loop continues to run and doesn't wait till the Tus(service) request completes).
When the  fileUpload request for a particular iteration is completed it's completion handler would be executed.

**Comment by StackHelp** [comment]
@MMasterson If we upload multiple files, Do we have to create separate sessions with separate `TUSFileUploadStore` using fileName?

**Comment by MMasterson** [comment]
Ah I see the issue now. You're right this should be handled better for multiple files.

The way I see it working now is waiting until one 1 file finishes before starting the next, but that's not the most optimal for anyone.

How do you envision this working for multiple files? Any suggestions would be appreciated!

@StackHelp @shravanteegala

**Comment by StackHelp** [comment]
@MMasterson Right now the main issue I am facing is to know which files progress is this when there are multiple uploads. Let's say I have 5 files to upload right now. Now I do know that I have 5 files selected that to be upload and creates upload with `tusUpload = tusSession?.createUpload` something like this 

       
        for file in pendingFiles  {
            tusUpload = tusSession?.createUpload(fromFile: URL(string: file.mediaPath)!, retry: -1, headers: nil, metadata: metaData)
            tusUpload?.progressBlock = { bytesWritten, bytesTotal in
                // Update your progress bar here
                print(String(format: "progress: %llu / %llu", UInt64(bytesWritten), UInt64(bytesTotal)))
                print("PROGRESS ID: \(self.tusUpload?.uploadId)")
                print("FILE: \(file.fileName)")
                self.progressUpload(with: file.fileName, bytesWritten: bytesWritten, bytesTotal: bytesTotal)
            }
        }


With this, I do know the progress file by checking filename which `Primary key` in my case. Till this, it's completely fine to check that this file changed the progress. But let's say I restarted the app without completed uploads for any of the files. Now, I have to get the data from the session using `restoreAllUploads`. Now, with this method, I don't have any reference to file that this file uploads right now and change progress. Any idea of how to handle this kind of situation?

**Comment by MMasterson** [comment]
@StackHelp  checkout this gist and let me know if you have any suggestions or additions you'd like to add

https://gist.github.com/MMasterson/15917ac9e7f7c04ae51c58ef95a9e0a8

**Comment by StackHelp** [comment]
@MMasterson Thanks for your time and the goals you set are just perfect for the new version. Just one addition if possible add `Cancel And Retry` function if any user wants to cancel the current process for a file and can easily start the new process at the same time. 

I like the way you make sure that with the id we can possibly refer file progress. That's perfect. If you want any help regarding anything related to it, I would like to help you. Thanks

**Comment by MMasterson** [comment]
I like the addition of retry and cancel. I see those as `TUSUpload` methods, as well as functions for the `TUSClient`. 

So adding

```swift
TUSUploadObject.cancel() ///Cancel the upload of a specific upload
TUSUploadObject.retry() ///Retry the upload of a specific upload

TUSClientObject.cancelAll() //Cancels all uploads
TUSClientObject.retryAll() //retires all uploads 

```

With that I changed the delegate to be return the `TUSUpload` object, so you can run these methods. You can always find the ID of an upload object with `TUSUpload.id`

```
func TUSProgress(bytesUploaded, bytesRemaining) //overall current upload progress

func TUSProgress(TUSUpload, bytesUploaded, bytesRemaining) //Per file upload progress

func TUSSuccess(TUSUpload, TUSResponse)

func TUSFailure(TUSUpload, TUSResponse, Error)
```

Trying to write most of it today, will create a new branch and show progress by end of the day

**Comment by StackHelp** [comment]
@MMasterson That's excellent. I wish I can help you. I know I don't have that much knowledge of you but definitely like to help you. This is excellent work by you.

**Comment by MMasterson** [comment]
@StackHelp no worries! The branch is over at `swift-development` - feel free to chime in with any kinda PRs.

Right now we have the basic outline of files and saving status' of uploads, just working on the networking to create and actually upload to TUS and we should be good. I'll put in some time tomorrow

**Comment by StackHelp** [comment]
@MMasterson ok. Let me check

**Comment by MMasterson** [comment]
discussion of Swift rewrite and modifications to current flow moved to #65
