### ISSUE TITLE
App extension support

### ISSUE THREAD

**Issue by foxware00** [tus/TUSKit#63]
I'm getting` 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.`

Is it possible, or, what would the best solution be?

I share my networking layer across Share Extension and my main application but am unable to compile the application when.

**Comment by MMasterson** [comment]
Got it! Checking your PR @foxware00, thanks for the addition!

**Comment by foxware00** [comment]
Thanks @MMasterson I've been playing with this anf the pr works well, but opens another problem with background sessions. I have a local branch where I'm working through migrating the session to support delegates so I can run in the background without throwing errors. It's not quite finished, and would potentially like your input whilst I finish the pr as I'm sure there are some assumptions in the library I'm overlooking. Not sure if you've had a play with this in the past or not?

**Comment by MMasterson** [comment]
@foxware00 Just saw your comments on #57 

I agree about the use of delegates and have been meaning to make the switch. I think another major change I've been toying around with is the switch over to Swift entirely, this is where I would make the change to delegates. Keep in mind when going down the background session path that iOS 13 is much more aggressive with killing tasks than ever before. 

I'd love to take a look at your current branch and see where it's taking you, see if we could have this in a better spot for the library sooner than later

**Comment by foxware00** [comment]
@MMasterson opened #66. It's a pretty simple change to get this to work although there seems to be a small issue with `self` breaking the upload from continuing
