### ISSUE TITLE
Upload to Vimeo : <TUSResumableUpload.m:(336)> Server responded to create file with 405

### ISSUE THREAD

**Issue by Geremp** [tus/TUSKit#68]
Hello,

Someone try to upload to vimeo a video with TUSKit ?

I try to use it but when i upload, i get this error :

> <TUSResumableUpload.m:(336)> Server responded to create file with 405

Below my code : 
`NSURL * applicationSupportURL = [[[NSFileManager defaultManager] URLsForDirectory:NSApplicationSupportDirectory inDomains:NSUserDomainMask] firstObject];
    
    TUSUploadStore * uploadStore = [[TUSFileUploadStore alloc] initWithURL:[applicationSupportURL URLByAppendingPathComponent:@"temp_vimeo_tus_upload"]];
    
    self.tusSession = [[TUSSession alloc] initWithEndpoint:[[NSURL alloc] initWithString:upload_url] dataStore:uploadStore allowsCellularAccess:YES];
    
    NSDictionary *dict_head = @{@"Tus-Resumable" : @"1.0.0",
             @"Upload-Offset":@"0",
             @"Content-Type" : @"application/offset+octet-stream",
                                @"Accept" :accept
    };
    
    TUSResumableUpload *upload = [self.tusSession createUploadFromFile:videoToUploadUrl headers:nil metadata:nil];
    
    
            upload.progressBlock = progressBlock;
            upload.resultBlock = resultBlock;
            upload.failureBlock = failureBlock;
    
            [upload resume];`

Maybe something that i don't understand

**Comment by Geremp** [comment]
It seems this lib try to create ressource to the server before upload.
But Vimeo API create itself the ressource on the server and return an url for the file upload.

So the only thing i need it to tell TUSKIT to upload this file to this url, without create the ressource.
Is that possible ?

**Comment by foxware00** [comment]
If you pass the upload URL you mention to `createUploadFromFile` as the last param I believe it skips the creation phase

**Comment by MMasterson** [comment]
Related to #44 and #45 

if you use the method `let upload = session.createUpload(fromFile: fileURL, headers: headers, metadata: nil, uploadUrl: uploadURL)` with `uploadURL` as the already created file it should solve your issue

**Comment by Geremp** [comment]
Thank you !
My bad… my pod repo wasn't update, so I hadn't the last version…
Know it's ok !!
