### ISSUE TITLE
No visible @interface for 'TUSSession' declares the selector 'createUploadFromFile:retry:headers:metadata:'

### ISSUE THREAD

**Issue by Geremp** [tus/TUSKit#69]
Hello,

I install TUSKit via POD.
It is Ok, but the interface TUSResumableUpload *upload = [self.tusSession createUploadFromFile:fileUrl retry:3 headers:@{} metadata:@{}]; not exist …

**Comment by MMasterson** [comment]
can I see how you've implemented the library?

**Comment by Geremp** [comment]
I can’t upload to Vimeo with this lib. So I did all the work by myself ... I remove all the lib. So I can’t show you how. 

But basically :
Run pod 
Then add #import. 
And use the code in the example.

**Comment by MMasterson** [comment]
You can upload to vimeo with the objc library using
`let upload = session.createUpload(fromFile: fileURL, headers: headers, metadata: nil, uploadUrl: uploadURL)` and uploadURL as the vimeo file url.

But no worries, if you choose to switch back to the library once a more stable swift version is released, feel free to ask any questions!

**Comment by Geremp** [comment]
Thank you !
My bad… my pod repo wasn't update, so I hadn't the last version…
Know it's ok !!

Thank you for your reply !
