### ISSUE TITLE
Support Customisation

### ISSUE THREAD

**Issue by ArkadiYoskovitz** [tus/TUSKit#7]
Recently I had to do some work on an iOS client for a server that use a customised implementation of the TUS  protocol.

Which forced me to do some work arsounds on the TUSKit copy that we used.

Therefore I'm asking you to make TUSKit itself more open to customisation. If you'll expose the Header parameter so that the user will be able to pass some extra headers to the POST, HEAD & PATCH requests then less hacking will be forced on the users.

After all while the TUS server protocol is great some people choose to add to it in their implementation which forces us poor client writes to do privet copies... which is the thing to avoid.

**Comment by Acconut** [comment]
Further development of this iOS client for tus is, sadly, not guaranteed yet since it depends on @michaelavila as discussed in #5. I would like to see your issue addressed but I can't do anything by myself at the moment.

**Comment by MMasterson** [comment]
@Acconut are there any plans for further development? Are there any major disadvantages with running the older version of TUS.io to support iOS? Is there any documentation to understand the workings of TUS.io for development of new 1.0 supportable iOS framework?

**Comment by MMasterson** [comment]
@ArkadiYoskovitz have you solved your issues? or any kind of work around? / alternative method?

**Comment by ArkadiYoskovitz** [comment]
Hi @MMasterson,
In the end i cloned the code and made a hack so that the TUS request holds a dictionary of headers.
and in the relevant places i add the headers from my dictionary to the request generated by TUSKit

**Comment by MMasterson** [comment]
@ArkadiYoskovitz Nice approach! do you have your a fork? May I pull request?

**Comment by ArkadiYoskovitz** [comment]
Unfortunately i did a copy/paste so no fork, but i can send you a copy of the files, whats your  email?

**Comment by MMasterson** [comment]
@ArkadiYoskovitz Thank you very much! mrobertmasterson@gmail.com

**Comment by Acconut** [comment]
@MMasterson I am happy to see that @ArkadiYoskovitz could help you in some of your regards. Sadly, the status did not change since my last comment:
> Further development of this iOS client for tus is, sadly, not guaranteed yet since it depends on @michaelavila as discussed in #5. I would like to see your issue addressed but I can't do anything by myself at the moment.

**Comment by kvz** [comment]
Maybe stating the obvious here but gents, if you'd want to help us push TUSKit forward your contributions will be much appreciated!

**Comment by MMasterson** [comment]
issue can be closed
