### ISSUE TITLE
Question : Delay from 20 to 30 sec before start upload

### ISSUE THREAD

**Issue by Geremp** [tus/TUSKit#70]
Hello,

I start to using this lib : TUSKit 1.4.2 in objective C.

It is working great.
But I see that i have a delay before the upload start : around 20 / 30 sec.
Do you know if it is normal ?

I am uploading to vimeo.
My android app start around 1 / 2 sec uploading.

my code : 
`NSURL * applicationSupportURL = [[[NSFileManager defaultManager] URLsForDirectory:NSApplicationSupportDirectory inDomains:NSUserDomainMask] firstObject];

    TUSUploadStore * uploadStore = [[TUSFileUploadStore alloc] initWithURL:[applicationSupportURL URLByAppendingPathComponent:@"temp_vimeo_tus_upload"]];

    self.tusSession = [[TUSSession alloc] initWithEndpoint:[[NSURL alloc] initWithString:upload_url] dataStore:uploadStore allowsCellularAccess:YES];

    TUSResumableUpload *upload = [self.tusSession createUploadFromFile:self.mP4Writer.videoPathToUse retry:3 headers:nil metadata:nil uploadUrl:[NSURL URLWithString:upload_url]];

            upload.progressBlock = ^(int64_t bytesWritten, int64_t bytesTotal){
            // Update your progress bar here
            NSLog(@"progress: %llu / %llu", (unsigned long long)bytesWritten, (unsigned long long)bytesTotal);
                
                if([self.delegate respondsToSelector:@selector(vimeouploader_progress:totalBytesExpectedToSend:)]){
                [self.delegate vimeouploader_progress:bytesWritten totalBytesExpectedToSend:bytesTotal];}
            };
                
            upload.resultBlock = ^(NSURL* fileURL){
                // Use the upload url
                NSLog(@"url: %@", fileURL);
                
                if(![self.mP4Writer.wVC.perso_activate isEqualToString:@"true"])
                {
                    [self embedVideoOnDomain:self->video_id];
                }
                else
                {
                    [self.delegate vimeouploader_succes:@"" methodName:self->video_id];
                }
            };
                
            upload.failureBlock = ^(NSError* error){
                // Handle the error
                NSLog(@"error: %@", error);
                
                if([self.delegate respondsToSelector:@selector(vimeouploader_error:methodName:)])
                {
                      [self.delegate vimeouploader_error:error methodName:@"error"];
                }
            };

            [upload resume];`

**Comment by Geremp** [comment]
Maybe the upload start but the progress is trigger when a big part of the file is upload ( I see in my exemple after 30 sec wait, the progress was trigger from 0 to 60%.)
It is possible to change chunk size ?

**Comment by Geremp** [comment]
I tested to set chunk size with : [upload setChunkSize:1024000];
I test 1Mo and 10ko
With this two, i can see my upload on the progress bar because upload.progressBlock is trigger more often.

But i see that the upload is very slow for a litte video : 3Mb, I test over wifi and 4G.
Maybe i miss some params for the session ?

**Comment by MMasterson** [comment]
hey @Geremp!

I will implement `Vimeo` uploading to the next update this weekend for the swift version and test upload speeds to make sure they're faster than v1

**Comment by Geremp** [comment]
Ok gréât. Let me know when it is working. 
I change the chunksize to 1.5Mb and it is fine. Not good but fine :-). 

Cordialement,

Jérémie PERERA

**Comment by Geremp** [comment]
Hello @MMasterson ,

Did you implement Vimeo upload in Swift TUSKit release ?
I am using your objective C version.

I have some problem : Sometimes, my app block during the upload, i have to relaunch it, and the upload resume.

I implement your TUSKit in : 
@interface Vimeo_uploader_tus : NSObject<NSURLSessionDelegate, NSURLSessionTaskDelegate>

Do you think that iOS Session can stop if the upload is to long ?

**Comment by elvirion** [comment]
I’m closing this issue because it has been inactive. We've recently released 3.0.0.
