### ISSUE TITLE
Issue when upload to Vimeo : TUSKit say success but vimeo waiting upload

### ISSUE THREAD

**Issue by Geremp** [tus/TUSKit#71]
Hello,

It is an issue I have, I wanting to know if you get this issue too…

I have uploading a video with TUSKit.
TUSKit block result is trigger, but Vimeo is still waiting the upload.

I asked Vimeo to see if if the problem is on their side.
But if someone have this issue… an help will be good :)

Is that possible that success block was trigger but to say that video is not upload ?

**Comment by elvirion** [comment]
I’m closing this issue because it has been inactive. We've recently released 3.0.0. Feel free to open a new issue if this issue remains on version 3.x.x.
