### ISSUE TITLE
Attempting to store >= 4194304 bytes of data in CFPreferences/NSUserDefaults on this platform is invalid

### ISSUE THREAD

**Issue by atomic991** [tus/TUSKit#73]
Hi,

I am using new swift lib for this awesome project but I am getting error when trying to store data in UserDefaults. So if we have video of 100MB do we really want to store that in user defaults? Is there any workaround for this issue?

Issue seems to be in TUSClient.swift on line 88 where it says:
try UserDefaults.standard.set(Data(contentsOf: path), forKey: tusName)

Thanks and keep up the good work

**Comment by MMasterson** [comment]
Switching back to file storage in the next update. We originally switch to UserDefaults to help some early adopters, but it did not hold up.

**Comment by atomic991** [comment]
@MMasterson Thanks for the feedback, any info when this could be resolved?

**Comment by MMasterson** [comment]
@atomic991 just published 2.1.0, this includes switching back storage of temporary files to the local file system. This should resolve your issue

**Comment by MMasterson** [comment]
@atomic991 let me know if you're still having issues here.
