### ISSUE TITLE
Why use UserDefaults store data

### ISSUE THREAD

**Issue by Lius1104** [tus/TUSKit#74]
I saw that the previous issue mentioned that FileManager is used to read sandbox files, and why userdefaults is used now.

Our app use scenario is to select up to 55 resources (pictures, videos, documents) at a time, of which the document size is limited to 100m and the video length is not limited. Is our app really suitable for using userdefaults to store the files to be uploaded?

In the demo of 2.0.7-alpha, I used the iPhone 11 Pro Max simulator

Operation steps:

1. Click "add file" to select a photo;

2. Click "upload files" and the progress bar hasn't changed. The debugging window hasn't printed any information. I don't know what's wrong

3. Run the app again, click "tlphoto" to select a picture, click "OK", and the app will crash directly

**Comment by MMasterson** [comment]
Switching back to file storage in the next update. UserDefaults did not hold up.

**Comment by MMasterson** [comment]
Switched back to file manager
