### ISSUE TITLE
How to get url of a uploaded mp4 files?

### ISSUE THREAD

**Issue by BasavarajIOS** [tus/TUSKit#77]
@MMasterson I have integrated Swift TUSKit in our project. We are able to upload the mp4 file and got url from httpResponse.allHeaderFields["URL"] (TUSExecutor file) without the .mp4 extension(like https://s3.ap-south-1.amazonaws.com/ans.video.input/transcode_input/video2020.2020/8/15/video2020_08_15_03_18_13_5370_1597484905). Without extension we are not able play the video.   Please help me find the solution ASAP.

**Comment by Acconut** [comment]
@MMasterson Could you help here? :)

**Comment by MMasterson** [comment]
@Acconut @BasavarajIOS 

Appending a .mp4 to the file will make it playable. @Acconut does the TUS protocol omit extensions?

**Comment by Acconut** [comment]
> does the TUS protocol omit extensions?

The protocol itself does not specific how the upload URL should be formed. This behavior can freely be chosen by the tus server that is used.

**Comment by hannojg** [comment]
This PR: https://github.com/tus/TUSKit/pull/95 will fix the issue

**Comment by MMasterson** [comment]
fixed in #95 - thanks @hannojg !!
