### ISSUE TITLE
Cant find pause option in master

### ISSUE THREAD

**Issue by nthrussell** [tus/TUSKit#81]
I was trying to create a button for pause action but its not there. What is the case for pause now please ?

**Comment by MMasterson** [comment]
Syntax would be `.cancel()` but seems I overlooked this, my apologies, will add in tomorrow!

**Comment by nthrussell** [comment]
Thank you for the response.

Yes I checked the `TusClient.shared.cancel()` option as well, its not complete yet. I could guess it cancel the current upload. But I was more interested in `TusClient.shared.pause()` option. Pause and resume is what I was looking for into this library. If that works that would be great for us. Thank you again

**Comment by MMasterson** [comment]
@nthrussell apologies been a bit busy with the new year, back to normal tomorrow

**Comment by MMasterson** [comment]
version `2.0.0` should close this one out!

**Comment by nthrussell** [comment]
Thank you very much @MMasterson
