### ISSUE TITLE
Getting error "don't have permission to access 'TUS'"

### ISSUE THREAD

**Issue by DevGirisankar** [tus/TUSKit#86]
Was trying to upload file to vimeo 
tried using picker and tried using bundle file, but getting the same error 

TUSKit: File not found in local storage.
Failed moving file file:///private/var/containers/Bundle/Application/562FC6BC-2C37-4753-93DC-B133CF566A0D/TUSKit_Example.app/test.mp4 to /var/mobile/Containers/Data/Application/32688A85-6D05-4F0B-BE18-DF34852DB478/Documents/TUS/video66.mp4 for TUS folder storage
“test.mp4” couldn’t be moved because you don’t have permission to access “TUS”.
TUSKit: Failed to move file.

Please help me

**Comment by MMasterson** [comment]
hey @DevGirisankar are you still having issues? Or have you figured this out?

**Comment by dannypier** [comment]
I'm intermittently seeing this issue as well. It seems to happen if I stop my app (during development) in the middle of an upload. Future uploads begin triggering this error. Happy to provide more info/debugging support.

**Comment by hannojg** [comment]
@dannypier can you try whether it still happens when installing the TUSKit pod from this dev branch:
```
Podfile
...
pod 'TUSKit', :git => 'https://github.com/hannojg/TUSKit.git', :branch => 'latest'
```

this contains all changes from https://github.com/tus/TUSKit/pull/90 and the other unmerged PRs I put up.
In these changes, background handling has been properly implemented (and they will be made available soon in a 2.1.0 version, having some testing here before creating the release would be great :))

**Comment by yunustek** [comment]
Hi I'm using v2.1.0 but the issue still continues. Error is that:

```
TUSKit.TUSResponse(message: Optional("Failed moving file /private/var/mobile/Containers/Data/PluginKitPlugin/E79CD3FE-F75F-41C6-9717-129B089E7E7A/tmp/trim.973EC64D-B19F-49A1-A551-10469C9C7AE5.MOV to /var/mobile/Containers/Data/Application/6C550D0B-84D2-48B4-A022-48DE23757895/Documents/TUS/bv4jms1ndfvm2a2l84k0_trim.973EC64D-B19F-49A1-A551-10469C9C7AE5.mov for TUS folder storage")))
```

```
"The file “trim.973EC64D-B19F-49A1-A551-10469C9C7AE5.MOV” couldn’t be opened because you don’t have permission to view it."
```

**Comment by elvirion** [comment]
I’m closing this issue because it has been inactive. We've recently released 3.0.0. Feel free to open a new issue if this issue remains on version 3.x.x.

**Comment by yunustek** [comment]
I already tried on version 3.1.3 still same

> Hi I'm using v2.1.0 but the issue still continues. Error is that:
> 
> ```
> TUSKit.TUSResponse(message: Optional("Failed moving file /private/var/mobile/Containers/Data/PluginKitPlugin/E79CD3FE-F75F-41C6-9717-129B089E7E7A/tmp/trim.973EC64D-B19F-49A1-A551-10469C9C7AE5.MOV to /var/mobile/Containers/Data/Application/6C550D0B-84D2-48B4-A022-48DE23757895/Documents/TUS/bv4jms1ndfvm2a2l84k0_trim.973EC64D-B19F-49A1-A551-10469C9C7AE5.mov for TUS folder storage")))
> ```
> 
> ```
> "The file “trim.973EC64D-B19F-49A1-A551-10469C9C7AE5.MOV” couldn’t be opened because you don’t have permission to view it."
> ```

**Comment by tursunovic** [comment]
@yunustek ,

Looks like you are trying to obtain a resource after using the system's built-in image picker. Could you indicate how you are using it, or share the integration code? And are you able to reproduce this with any kind of resource that you pick (e.g. small image and large videos)?
