### ISSUE TITLE
1.4.2 -> 2.0.0 Migration

### ISSUE THREAD

**Issue by dfmarulanda** [tus/TUSKit#94]
I've been trying to upgrade from 1.4.2 to 2.0.0. The project had a lot of changes, both, in how it's implemented on the backend and how you use it on iOS. I decided to keep 1.4.2 as the new version have almost no documentation and the different methods (like using headers and retries) are almost at scratch. I'll have to get some time to read the new code and understand what are you trying to do to implement it as is expected. So, I want to know if you're planning to document this project or make a migration guide and if I'm going to have any problems if I keep using 1.4.2.

**Comment by MMasterson** [comment]
hey @Dfmarulanda 

There are a lot of open PRs to move the project forward and get it past the current state thanks to @hannojg - hoping to have all these merged and released by the weekend. After theses PRs are merged in I will update the README accordingly, and I can write up a migration guide from 1.4.2 to 2.1.0.

**Comment by Dfmarulanda** [comment]
It would be great! Indeed, after migrating I can try to contribute to the project a little bit. I'll be waiting for the upcoming release!

**Comment by MMasterson** [comment]
hey @dfmarulanda 

the new version is live and I'll have a migration guide up for you this weekend with updated docs!

**Comment by aravasio** [comment]
Any updates on this migration guide from 1.4.2?

**Comment by dfmarulanda** [comment]
Hello?

**Comment by ccparram** [comment]
I would love to see that migration guide!

**Comment by Acconut** [comment]
Apologies for the delay! We are currently waiting for our new maintainer to begin working on TUSKit at the beginning of September. I am afraid we have to wait with an update until then as I don't know any Swift :)

**Comment by elvirion** [comment]
I’m closing this issue because it has been inactive and we've recently released 3.0.0.
